### ISSUE TITLE
Implement progress reporting 

### ISSUE THREAD

**Issue by mpickering** [digital-asset/ghcide#100]
When you start `ghcide` is just looks like it hangs. It would be good to report progress to the client using the `withProgress` functions from `haskell-lsp`.

**Comment by cocreature** [comment]
We should already support progress reporting if the client advertises it, see https://github.com/digital-asset/ghcide/blob/a162e81aa306c8efe2be3ce0d591f46abd5f88e4/src/Development/IDE/Core/Shake.hs#L305

**Comment by ndmitchell** [comment]
FWIW, I've yet to see this when using VS Code.

**Comment by mpickering** [comment]
There should also be a progress report during initialisation. It takes over a minute to initialise ghc where the IDE is  unresponsive.

I also can't observe the progress notifications working as they should after looking at the code.

**Comment by cocreature** [comment]
Do you mean `hie-bios` initialization? The actual loading up the modules part in `ghcide` should be tracked. I think the reason why this isn’t working (it’s definitely working for DAML) might actually be an issue in the VSCode extension. iirc we needed to bump some dependency to an experimental version and enable experimental features for the DAML extension for this to be activated so presumably we need to do the same here.

**Comment by ndmitchell** [comment]
It would be nice if it said "Loading Haskell Environment..." so you knew that it was doing something and could see when that had completed.

**Comment by domenkozar** [comment]
Besides the initialization, there's a question I ask myself constantly: did this compile successfully and there are zero problems or is it still compiling? On bigger projects, this becomes more relevant as compile times aren't instant.

**Comment by cocreature** [comment]
https://github.com/digital-asset/ghcide/pull/153 is a draft PR based on my WIP patches to `haskell-lsp`. It needs quite a bit of work to be ready (mostly on the `haskell-lsp` side) but in my limited testing it seems to work so feel free to try it out.

**Comment by cocreature** [comment]
This should be fixed in the new release of `ghcide` and the VSCode extension (you need to update both).
