### ISSUE TITLE
Performance of hover seems very poor

### ISSUE THREAD

**Issue by mpickering** [digital-asset/ghcide#101]
Compared to hover in `haskell-ide-engine` I think the performance of hovering over a symbol seems very poor. It seems to take up to 1s to process the request when the information can be precomputed for an entire module.

**Comment by mpickering** [comment]
Reload performance is very good though :+1:

**Comment by cocreature** [comment]
Hover works in two steps:
1. We have a rule for getting a list of source spans from a module https://github.com/digital-asset/ghcide/blob/32a049cc4c61961088cdd74ea0ebaa9d4ce596ff/src/Development/IDE/Core/Rules.hs. This rule is cached so if is slow on the second hover in the same module (without modifications) this shouldn’t be the bottleneck.
2. Based on that list, we then filter it to the ones at a given location, see https://github.com/digital-asset/ghcide/blob/32a049cc4c61961088cdd74ea0ebaa9d4ce596ff/src/Development/IDE/Spans/AtPoint.hs#L58. That filtering is an incredibly stupid search that is linear in the number of source spans. A very easy improvement here would be to replace the list by an interval map.

**Comment by ndmitchell** [comment]
The code is also used for goto definition, and there it doesn't seem great at finding all the relevant definitions either. This piece seems something that hie, intero and ghcide should all be able to share - something like:

```
findIdentifierAtLocation :: Module -> (Location -> [Identifier])
```

Where you do meaningful caching after seeing the module. I think the ghcide code originally came in from Intero, but then got tweaked a fair bit. Is there scope for sharing? Who does it best? Could the hie code become hie-spans and then be shared/improved by all?

**Comment by mpickering** [comment]
Here is the code which generates the `TypeMap` in `haskell-ide-engine`. 

https://github.com/haskell/haskell-ide-engine/blob/ff9a5b2e85a0910205cb781bf630503efe6bd227/hie-plugin-api/Haskell/Ide/Engine/TypeMap.hs#L1

Definition map:

https://github.com/haskell/haskell-ide-engine/blob/6254c09fbc909dca2673ad7a27fe082dc75d6fc9/hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs#L119

**Comment by mpickering** [comment]
Also another implementation of a definition map from my branch with less CPP using pattern synonyms.

https://github.com/mpickering/haskell-ide-engine/blob/hie-bios/hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs#L88

**Comment by ndmitchell** [comment]
@mpickering - which would you recommend? Are they basically the same with less CPP in one?

**Comment by mpickering** [comment]
Yes they are the same but just refactored to remove the CPP from the second one.

**Comment by mpickering** [comment]
I hacked together an implementation using the `TypeMap` from `h-i-e` but the performance is only a little bit better. I don't really know why though, it still takes up to a second for each request. Can we use any shake profiling features to accurately work out where the time is taken?

**Comment by cocreature** [comment]
Shake profiling only gives you timings for rules. The part after finding the source spans which should be the issue here is not part of a rule so it won’t show up in the profile.

**Comment by mpickering** [comment]
I ran a profile with my modified branch and it seems that the `GhcSessionIO` command dominates the time taken to calculate hover. 

http://mpickering.github.io//ide-20190924-104338-00002-1.56.html

**Comment by mpickering** [comment]
I pushed my branch here - https://github.com/mpickering/ghcide/tree/wip/type-map

I don't plan to look into this any further at the moment.

**Comment by cocreature** [comment]
As mentioned in IRC, the bottleneck in this profile is `GetFileExists`. Weirdly, we seem to be calling `GetFileExists` 5891 times while we call `GetModificationTime` only 60 times. It looks like the issue is that we are calling `GetFileExists` once per file * include dir.

**Comment by mpickering** [comment]
I tried removing the lhs file support and it indeed made the request twice as fast.

**Comment by ndmitchell** [comment]
Wow. How many files are there? I'm guessing about 60? And how many include directories? 50 seems like an insane amount. The "correct" thing to do is check which files might impact the result, and that requires checking each file everywhere on the include directory before we found it, which is what we do.

**Comment by ndmitchell** [comment]
No disagreements that 4s is unacceptable. Thinking of ways to reduce that:

* It stops doing doesFileExist queries as soon as it encounters the files, so by putting the "right" directories first you should be able to massively reduce that.
* 25 include dirs is just silly. GHC should use hierarchical module names like the rest of the planet.
* Why is querying for file existence so slow? It seems more expensive than I expect, given it should be served by the file system cache.
* We could alter the dependencies so it looks for the files, then only if the file changes it will rehunt for them.
* We could alter the dependencies so that once a file has been found, we consider that the file location forevermore.
* We currently get information from VS Code that "something has changed, I don't care what" - if instead we actually used the information we could skip both file existence and modification checks.
* We could use the stale information when computing the hover request, rather than forcing it to be up to date. We could even do something like getting the file modification time, and saying that if the file hasn't been modified since the last value we have, that's always the right thing to do.

**Comment by mpickering** [comment]
@ndmitchell GHC is moving towards a hierarchical module structure so this might be less of an issue within the next few months. 

I still imagine this might be a problem though if build tools keep creating super components, you could easily imagine a mono-repo with 25 different libraries which would mean 25 different `-i` options. At least some configuration option for faster but less precise behaviour would be useful immediately and potentially useful in future. Which of your choices do you think is easiest to implement?

**Comment by ndmitchell** [comment]
Quickest to implement is change https://github.com/digital-asset/ghcide/blob/60ed687de93393d2b71c96b0b49ff2a2997f62a7/src/Development/IDE/Core/Rules.hs#L158 from `getFileExists` (tracked) to `liftIO . doesFileExist`. Report back what happens - it's not an unreasonable change, and only slightly less correct.

**Comment by mpickering** [comment]
@ndmitchell With my other changes, that makes responses generally take between 0.2 and 0.5s which doesn't feel too slow. 

1. Use the `TypeMap` rather than SrcSpanInfo
2. Remove the `"lhs"` extension from the search

The response still seems to scale linearly but not as bad as with the tracked `doesFileExist`.

**Comment by ndmitchell** [comment]
I'd rather we aim for < 0.1s, if we can, so would be keen to know what the remaining profile looks like. Does removing the `lhs` still give a win in conjunction with doesFileExist?

**Comment by mpickering** [comment]
Still seems generally faster (0.2-0.3s in total) removing `lhs`.

**Comment by cocreature** [comment]
The DAML repo is one of those monorepos that we want to load as a super component with a lot of include dirs so I very much care about the performance in the case of lots of import paths.

@ndmitchell I guess the correctness issue you mentioned is the one where you add/remove/move files between include dirs and won’t pick up those changes? That seems like an acceptable issue given the performance gains (of course if we find a way to get these gains without compromising on correctness that’s even better).

**Comment by mpickering** [comment]
Can we use `fsnotify` to watch the include dirs for changes? Then you don't need to do any of this searching at all.

**Comment by ndmitchell** [comment]
`fsnotify` seems like the right way to go, and also saves on modification time checking too.

**Comment by ndmitchell** [comment]
@cocreature some of move/remote/add would go wrong. Given only doing modification time checks, you should be able to reduce that to only going wrong when you put a new file on the include path with the same name, before the file that exists.

**Comment by ndmitchell** [comment]
I'd still like to understand why removing `lhs` doesn't make it go any faster. It could well be that what we're seeing isn't the doesFileExist times, but actually that Shake has some overhead per node. And if so, reducing that to nearly zero benefits everything and gives us correctness.

If someone did some doesFileExist's in a loop and proved that alone was too slow, I'd feel happier with building hacks for other bits.

**Comment by mpickering** [comment]
Removing `lhs` does make it go about twice as fast.

**Comment by ndmitchell** [comment]
* Sorry @mpickering I typo'd the wrong negation there.

**Comment by ndmitchell** [comment]
I just ran 100K doesFileExist tests on the same directory, where 70K of them actually existed. Total time was 0.53s. This was a Mac SSD. At 20K GHC is making, we shouldn't be seeing 4s.

**Comment by mpickering** [comment]
I'm not sure what to make of this information @ndmitchell - what are you suggesting about the problem?

**Comment by ndmitchell** [comment]
It seems at least on my machine you get a big slowdown which is quite a bit bigger than the slowdown I'd expect from the extra doesFileExist calls alone. Where has the extra slowdown come from? Or is your machine having different performance results for doesFileExist?

**Comment by mpickering** [comment]
If you give me your benchmark I can try, or you can try using `ghcide` on GHC, all the configuration files reached master yesterday. I have been loading `ghc/Main.hs`.

**Comment by ndmitchell** [comment]
Me trying `ghc/Main.hs` seems like a worthwhile thing to do. I'm guessing it isn't going to work on Windows?

```
ghcide.exe: C:\Neil\ghc\2019-09-26\ghc\hadrian\hie-bios: readCreateProcessWithExitCode: invalid argument (Exec format error)
```

**Comment by mpickering** [comment]
Someone has got it to work on windows before, you just need to change the `hadrian` invocation probably.

**Comment by ndmitchell** [comment]
Seems my attempts get thwarted by Hadrian: https://gitlab.haskell.org/ghc/ghc/issues/17249

**Comment by wz1000** [comment]
I think this LSP notification might allow getting rid of the `doesFileExist` calls: https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#workspace_didChangeWatchedFiles

**Comment by ndmitchell** [comment]
@wz1000 that's a _way_ better approach. Might be a fair amount of work to convert over, and we'd need to figure out how it interacts with the existing haskell-lsp file store abstraction, but worth it.

**Comment by mpickering** [comment]
Is the plan to use the the LSP request immediately or in the short term add an option to disable `lhs` and the use of `getFileExists`?

**Comment by cocreature** [comment]
I took a look at the LSP request and it doesn’t look too bad to implement:

1. We can keep a global map that is something like `Map FilePath (Map ModuleName [(FilePath, Maybe FileVersion)])`. That map tracks for each file and import in that file the version of all candidates using `Nothing` if the candidate does not exist (we probably want something better than just a list and probably cache the candidate that the import would currently resolve to, this is just a sketch).
2. When we locate a module for the first time, we go through the include dirs and update this map based on information on disk. We also register a file watcher for all possible candidates.
3. When the client notifies us that a file has changed (including creations and deletions), we update the map.
4. Whenever we locate a module, we first check if we already have an entry in the map, if not we fall in the case described in 2, otherwise we use the information from the map and never hit the disk.

It looks like client support for this is pretty good, VSCode, emacs’ `lsp-mode` and `vim`’s coc all seem to support it so I would be fine with adding this without having a fallback to something like inotify and just keep falling back to case 1 everytime which would match our current behavior roughly. But if we want to add some kind of inotify fallback it seems reasonably easy to abstract this in such a way that inotify provides the events.

**Comment by ndmitchell** [comment]
Looks like a sane plan.

What I didn't see how to do easily was to eliminate the race between declaring we are interested in a file and the LSP client registering the callback. What if the file changes in that window?

**Comment by pepeiborra** [comment]
Is anyone working on this? If not, I might have a go. Current performance on large codebases like ours is not great.

**Comment by cocreature** [comment]
I don’t think anyone has started working on this so far.

**Comment by mpickering** [comment]
Hover performance is still quite poor. 1s for a hover request is still too high. At Bristol Hack I isolated a repeated a call to `getSpanInfos` to see why the response is taking too much time. The profile can be loaded into [speedscope.app](https://speedscope.app). 

https://gist.github.com/mpickering/02d7440d2266ef6b55b8532babea41d9

Running a profile on 1000 calls to `getAtPoint` shoes that time is dominated by the file conversion functions in `updateDiagnostics`. In particular, the URI escaping functions from `network-uri` dominate the runtime, 40% of executation time is spent in the [`isReserved`](https://hackage.haskell.org/package/network-uri-2.6.1.0/docs/src/Network-URI.html#isReserved) function from network-uri! 

<img width="1104" alt="Screen Shot 2020-01-26 at 22 56 40" src="https://user-images.githubusercontent.com/1216657/73143206-2b596000-408f-11ea-8f3d-764b931eceb9.png">

**Comment by alanz** [comment]
As I said at the hackathon, I think hover should be decoupled from the demand-driven stuff, and return immediately if there is nothing available, either reporting based on last-good info, or just nothing.

**Comment by mpickering** [comment]
@alanz I agree but this latency probably exists for every request so it makes sense to optimise it if possible. I imagine almost all the work is wasted by converting the filepaths over and over again.

**Comment by alanz** [comment]
@mpickering Agree with you, the path needs to be optimised, but also decoupled.

**Comment by mpickering** [comment]
See https://github.com/haskell/network-uri/pull/46

Unrolling the loop takes the 1000 hover benchmark from 259 seconds to 170 seconds. 

This is why we need multi-stage programming languages...

**Comment by mpickering** [comment]
Caching the call to `filePathToUri'` is probably the right fix, similar to what @pepeiborra suggested on https://github.com/digital-asset/ghcide/pull/373

**Comment by mpickering** [comment]
If I cache the conversion to `NormalizedUri` the time goes down to 44s.

**Comment by mpickering** [comment]
Patch: https://github.com/mpickering/ghcide/commit/b7b389e847e985e80ead4f6de04630a2ea0ecc6e

**Comment by mpickering** [comment]
I tested on `ghc` and the hover time is down to about 0.1s which is quite good. The profile is now dominated by calls to comparing `Uri`s, I wonder if we could do better here as well but I didn't investigate much yet. I will try to find time to prepare a patch tonight or tomorrow.

**Comment by ndmitchell** [comment]
What is causing us to compare Uris? The insertion into Map? If so, we could take a GHC Fingerprint of the Uri and use that for equality, then we have constant time comparison.

**Comment by mpickering** [comment]
@ndmitchell It comes from the call to `updateDiagnostics` so the code is in `haskell-lsp`. I  have some ideas about how to fix it I am going to try tonight.

**Comment by ndmitchell** [comment]
Looking at that code, the use of DiagnosticStore at all seems a little weird. There are three fields that look pretty similar:

```
    ,diagnostics :: Var DiagnosticStore
    ,hiddenDiagnostics :: Var DiagnosticStore
    ,publishedDiagnostics :: Var (Map NormalizedUri [Diagnostic])
```

I'd guess they should be a single `Var (Map NormalizedUri record-containing-all-three)`. The DiagnosticStore seems not a very useful abstraction. That presumably triples the number of key lookups, if not more.

**Comment by mpickering** [comment]
Hover time is between 0.1 and 0.2s which is still too high imo but at least usable unlike when this ticket was opened. If we want to make further improvements on this front it will have to come from within `ghcide` and callling things like `updateDiagnostics` less times I think.
