### ISSUE TITLE
Test initialization response

### ISSUE THREAD

**Issue by jacg** [digital-asset/ghcide#105]
It would appear that `ghcide` is not advertising its code action capabilities (emacs-lsp/lsp-ui/issues/319).

Consequently, I would like to add some tests which verify exactly what `ghcide` has to say at the time it is initialized. Could some kind soul who is more familiar with the APIs of `Haskell.Language.LSP` and `Development.IDE.LSP` (and whatever else might be useful) give me some pointers on how best to structure these?

**Comment by cocreature** [comment]
iirc `lsp-test` consumes the initialization response internally so I’m not sure there is a reasonably easy way to test this.

**Comment by cocreature** [comment]
Hi @jacg, I just took another look at this and it looks like it’s not as bad as I thought: `lsp-test` provides a [`initializeResponse`](https://hackage.haskell.org/package/lsp-test-0.7.0.0/docs/Language-Haskell-LSP-Test.html#v:initializeResponse) helper to access the initialization response so this should be reasonably easy hopefully.
