### ISSUE TITLE
Mask GHC session creation

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#109]
At the moment, if the user is using the API for real, and queries some in during GC session init then we abort the init (with an async exception) and restart doing something with a 99.9% change that it will do the same init from scratch. A mask here is a bit grim, but perhaps gives us the semantics we are after. The other choice is to fork GHC init on a separate thread and thus continue from where we left off cheaply.

I have a suspicion that some of the weird linker errors on startup might be the fact that GHC doesn't like being aborted during init.

**Comment by cocreature** [comment]
Just to make sure I understand what exactly you are proposing here, you want to mask the body of `GhcSessionIO` and `GhcSession`? If so that sounds sensible.

**Comment by ndmitchell** [comment]
Making the bodies of those rules `mask` doesn't massively help - you end up throwing just before you write the results into the big Map, so you avoid killing them in the middle, but still repeat them. You could extend that all the way to writing the rules back, but that seems dangerous that you would over-mask. The other option is to make the code in Main more complex, probably spawning them as a thread, and then waiting for the answer. You can still async exception it, but when you restart next time it will have been working in the background for you.

**Comment by ndmitchell** [comment]
memoIO in https://github.com/digital-asset/ghcide/pull/127/files, plus creating the initial IO masked, seems to be everything that's required to do it from the outside. Given how easily abstracted it was, I'm disinclined to push the mask further down.

**Comment by ndmitchell** [comment]
This got fixed in #127
