### ISSUE TITLE
ghcide fails to find dependencies under haskell.nix

### ISSUE THREAD

**Issue by matthewess** [digital-asset/ghcide#116]
I'm attempting to use ghcide in a project that uses [haskell.nix](https://input-output-hk.github.io/haskell.nix) and a new-style cabal project, but it seems like ghcide has trouble finding the packages provided by my nix environment. In a nix-shell:
```bash
$ ghcide
Starting ghcide (GHC v8.6)
/Users/mess/Development/pynchon
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "/Users/mess/Development/pynchon", cradleOptsProg = CradleAction: cabal}

[2/6] Converting Cradle to GHC session
ghcide: <command line>: cannot satisfy -package-id flow-1.0.18-LszYL0CVUH27sWuuO4w4S1
    (use -v for more information)
```

However, `cabal new-build/repl` work fine, and `ghc-pkg list` shows that flow (or whatever other package I attempt to include in my `.cabal` file) is present and working.

GHC 8.6.5, cabal 2.4.1.0

Any other information I can provide to help diagnose is gladly fetched.

**Comment by cocreature** [comment]
Hi,
which `cabal v2-repl` command are you using and what are the contents of your `hie.yaml`? Maybe they correspond to different components?

Also do you have a `.ghc.environment` file?

**Comment by mpickering** [comment]
You probably need to run `ghcide` from inside the same `nix-shell` that you run `cabal new-build` in.

**Comment by mpickering** [comment]
The other possibility is that you are using `ghcide` built with a different version of GHC?

**Comment by matthewess** [comment]
@cocreature I'm simply running `cabal new-repl`, to load all of the components, but `cabal new-repl . I'm not currently using an `hie.yaml`, but I briefly used something like:
```yaml
cradle: {cabal: {component: "lib:pynchon"}}
```
and got the same issue. No `.ghc.environment` file, I disabled their generation in my `cabal.project` because it has caused problems for me in the past. Is that file necessary?

@mpickering my workflow is to run `nix-shell --run "code ."` to get a vscode instance that has access to all of my nix-built tools. I'm using `ghcide-ghc865` from [ghcide-nix](https://github.com/hercules-ci/ghcide-nix), and the `ghc` provided by haskell.nix is indeed 8.6.5. I used niv to manage my nix expression dependencies, and my haskell.nix setup is pretty standard, but I can share my nix config if that might help?

**Comment by cocreature** [comment]
@matthewess The log output appears to be from running `ghcide` in a terminal instead of via VSCode. Have you also done that in a `nix-shell`? Is `flow` available via the global package env provided by new-build (what does `ghc-pkg list` inside the nix-shell show) or is it built via cabal?

**Comment by matthewess** [comment]
Yes, I’m using ghcide in the “test bed” mode to verify it works. All of these are being run in vscodes integrated terminal, which inherits the nix shell environment. flow is indeed listed in `ghc-pkg list`, run in the same shell that i ran ghcide in.

**Comment by matthewess** [comment]
That said, the behavior of all commands is identical in a simple `nix-shell` as well

**Comment by domenkozar** [comment]
See #137

**Comment by matthewess** [comment]
Finally got back around to looking at this. I get more interesting output from `ghcide` if I first `export NIX_GHC_LIBDIR=$( $NIX_GHC --print-libdir )` as recommended in a link from #137: https://gist.github.com/matthewess/281498e5c099165988568a7d402d7a77

The remaining errors/issues ghcide raises are related to test files and my cabal setup file, which I imagine can be resolved by instructing `ghcide` to ignore these in my `hie.yaml` somehow?
