### ISSUE TITLE
hie-core: hoogle integration?

### ISSUE THREAD

**Issue by meditans** [digital-asset/ghcide#12]
Would it be possible to use a hoogle database when the identifiers are not found inside the current set of modules? That would perfect the user experience for the `go-to-definition` feature.

**Comment by lorenzo** [comment]
Are those extensibility points documented somewhere? I'd like to play with those

**Comment by ndmitchell** [comment]
Not really, but if you look at the https://github.com/digital-asset/daml repo it uses them to build on hie-core. You can put new things on to the dependency graph like at https://github.com/digital-asset/ghcide/blob/master/src/Development/IDE/Core/Rules.hs#L328-L346 and define new types of handler by adding to PartialHandler in https://github.com/digital-asset/ghcide/blob/788b2124029cf17eae7cbb138554ed218ef80ab7/src/Development/IDE/LSP/LanguageServer.hs#L43 when calling it.

**Comment by ndmitchell** [comment]
I think Hoogle integration would be a feature of https://github.com/haskell/ide, as per https://neilmitchell.blogspot.com/2020/01/one-haskell-ide-to-rule-them-all.html

**Comment by cocreature** [comment]
I can’t transfer this for some reason so feel free to reopen over there.
