### ISSUE TITLE
Support custom preprocessors

### ISSUE THREAD

**Issue by cocreature** [digital-asset/ghcide#124]
Currently custom preprocessors such as `hspec-discover` are not supported. We should change that.

**Comment by madgen** [comment]
This will involve at the very least finding where the preprocessor lives which depends on the path and subsequently the build tool `stack exec`, `cabal exec`, etc.

If I understand it correctly, for that information `ghcide` entirely relies on `hie-bios`, but that only seems to find the flags passed to `ghc` but not the overwritten environment variables such as `$PATH`.

Then does that call for a `hie-bios` like project that collects the environment?

**Comment by ndmitchell** [comment]
@madgen quite possibly, yes. Although I think there's value even if it didn't, since at least then you can put them on your PATH globally to get things working.

**Comment by ndmitchell** [comment]
I think this is done through #192?

**Comment by cocreature** [comment]
Not through #192 but through #282 thanks!
