### ISSUE TITLE
mismatched interface file versions

### ISSUE THREAD

**Issue by willisplummer** [digital-asset/ghcide#135]
on a newly init'd stack project (`stack init test-project`), I'm getting the following errors when I run `ghcide`:

```
[6/6] Loading interesting files
[DEBUG] Finishing shakeRun (took 0.00s, exception: thread killed)
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
File:     ./test/Spec.hs
Range:    1:0-1:0
Source:   typecheck
Severity: DsError
Message: 
  test/Spec.hs:1:1: error:
  Bad interface file:
  /Users/willisplummer/.stack/programs/x86_64-osx/ghc-8.6.4/lib/ghc-8.6.4/base-4.12.0.0/Prelude.hi
  mismatched interface file versions (wanted "8065", got "8064")
File:     ./src/Lib.hs
Range:    1:7-1:10
Source:   typecheck
Severity: DsError
Message: 
  src/Lib.hs:1:8: error:
  Bad interface file:
  /Users/willisplummer/.stack/programs/x86_64-osx/ghc-8.6.4/lib/ghc-8.6.4/base-4.12.0.0/Prelude.hi
  mismatched interface file versions (wanted "8065", got "8064")
File:     ./Setup.hs
File:     ./Setup.hs
File:     ./Setup.hs
File:     ./Setup.hs
File:     ./Setup.hs
Range:    1:7-1:26
Source:   not found
Severity: DsError
Message: 
  Could not load module ‘Distribution.Simple’
  It is a member of the hidden package ‘Cabal-2.4.1.0’.
  You can run ‘:set -package Cabal’ to expose it.
  (Note: this unloads all the modules in the current scope.)
  It is a member of the hidden package ‘Cabal-2.4.0.1’.
  You can run ‘:set -package Cabal’ to expose it.
  (Note: this unloads all the modules in the current scope.)
File:     /Users/willisplummer/code/test-project/src/Lib.hs
Range:    3:12-3:14
Source:   typecheck
Severity: DsError
Message: 
  /Users/willisplummer/code/test-project/src/Lib.hs:3:13: error:
  Not in scope: type constructor or class ‘IO’
[DEBUG] Finishing shakeRun (took 0.01s, completed)
Files that worked: 0
Files that failed: 4
 * ./Setup.hs
 * ./app/Main.hs
 * ./src/Lib.hs
 * ./test/Spec.hs
Done
```

running `stack build` gives me no problems though

**Comment by cocreature** [comment]
That error is caused by the fact that you are using a different version of GHC on your project (looks like 8.6.4) than you used to build `ghcide` (8.6.5). This is not supported (and can’t be). You have to make sure that you build `ghcide` with the same version of GHC, e.g., by changing the resolver of the `stack.yaml` file in this repo to the one you are using for your project.

**Comment by willisplummer** [comment]
Oh I see. For a company that has many haskell projects with various resolvers, is there a plan for a way to support multiple versions of GHC simultaneously?

**Comment by cocreature** [comment]
There are some ideas for having a wrapper script that picks the right version of GHC automatically see #57 but it isn’t easy to get this right.

**Comment by PierreR** [comment]
On nix with cabal I have an similar issue.
All the haskell dependencies (except those from base) are not found. 

`cabal build`, `ghci` also has the dependencies. There are found thanks to shell.nix that configure ghc with `pkgs.haskellPackages.ghcWithPackages`.

Is there some tricks to make this work ? (stack works without problem but requires me to download a massive amount of haskell packages).

**Comment by ndmitchell** [comment]
@PierreR - are they not found, or have a version number mismatch? Is https://github.com/digital-asset/ghcide/blob/master/docs/Setup.md#issues-with-nix relevant?

**Comment by PierreR** [comment]
@ndmitchell to be honest I am totally lost ... The first error was about deps that were not found but then today trying it again I am getting something so weird : https://paste.ee/p/UVmyD
Why on earth is it telling me that the cradleDir is another unrelated dir ?

**Comment by PierreR** [comment]
Alright I remember now. I need a hie.yaml file with cabal:

Here is the error:
```
λ  cicd/puppet/unit-test at  pre-commit-hook  ^?
→ ghcide                                                                                                                                                                                                                                   1 ↵
Starting ghcide (GHC v8.6)
/home/vagrant/projects/bric/cicd/puppet/unit-test
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "/home/vagrant/projects/bric/cicd/puppet/unit-test", cradleOptsProg = CradleAction: cabal}

[2/6] Converting Cradle to GHC session
ghcide: <command line>: cannot satisfy -package-id aeson-1.4.4.0-mHKymN7k4k51cE7lc3Pkq
```

**Comment by PierreR** [comment]
@ndmitchell Thanks to the link you provided, I have managed to make it work by adding `NIX_GHC_LIBDIR ` the `shellHook` of my shell.nix. Thx !

**Comment by ndmitchell** [comment]
Great to hear it!

**Comment by PierreR** [comment]
@ndmitchell currently everything works as expected if I type `code` in the terminal on the project directory. But nothing works at all if `vscode` has been started before from another directory. This is a big awkward because I usually use a single instance of vscode.
 
This issue is probably more related to vscode than ghcide but just in case someone has some idea about it. I hope I am not hijacking this issue too much. Sorry about that. Maybe it is worth a separated issue ? Are you ok about asking help via github issue or should I use another mean ?

**Comment by ndmitchell** [comment]
Github for help tickets is just fine - and do feel free to move to fresh tickets for fresh issues.

My guess is your shell is being setup via Nix, but when you run vscode it isn't. One option would be to adjust the ghcide VS Code extension settings to run inside a Nix shell. https://github.com/digital-asset/ghcide/blob/master/docs/Setup.md#works-in-ghcide-but-not-my-editor lists two solutions - one is what you are running now, the other is what might be worth trying.

**Comment by i-schuetz** [comment]
Hi! I see to have the same issue described with `Stack`. What I did:

- Created a new Stack project with `stack new testproj`
- Set the same resolver as this project (`nightly-2019-09-16`) in `stack.yaml`
- Built with `stack build`
So far so good.

- Ran `ghcide`
Output:
```
testproj $ ghcide
ghcide version: 0.0.5 (GHC: 8.6.5)
Ghcide setup tester in /..../testproj.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /..../testproj
Found 4 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /..../testproj
Cradle {cradleRootDir = "/..../testproj", cradleOptsProg = CradleAction: stack}

Step 4/6, Cradle 1/1: Loading GHC Session

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files
File:     Setup.hs
Hidden:   no
Range:    1:7-1:26
Source:   not found
Severity: DsError
Message: 
  Could not load module ‘Distribution.Simple’
  It is a member of the hidden package ‘Cabal-2.4.0.1’.
  You can run ‘:set -package Cabal’ to expose it.
  (Note: this unloads all the modules in the current scope.)
Files that failed:
 * ./Setup.hs

Completed (3 files worked, 1 file failed)
```

**Comment by ndmitchell** [comment]
Thanks @i-schuetz - I think the comments give in https://github.com/haskell/haskell-ide-engine/issues/1093 apply to ghcide too, since we both use the same underlying library hie-bios which is causing a failure of Setup in both cases. With the warning that ghcide doesn't (yet) support multi-component hie-bios files.

**Comment by gvolpe** [comment]
Hi @ndmitchell ! Do you know if there's any workaround for this error? Probably some filter in `CocConfig` to avoid `Setup.hs` from being read? (using Neovim + Coc.nvim)

This is my current config:

```json
    "haskell": {
      "command": "ghcide",
      "args": [
        "--lsp"
      ],
      "rootPatterns": [
        ".stack.yaml",
        ".hie-bios",
        "BUILD.bazel",
        "cabal.config",
        "package.yaml"
      ],
      "filetypes": [
        "hs",
        "lhs",
        "haskell",
        "cabal"
      ]
    }
```

Thanks!

**Comment by ndmitchell** [comment]
No idea I'm afraid. I'm a VS Code user, where it doesn't have a very big impact.
