### ISSUE TITLE
hie-core: Vim integration

### ISSUE THREAD

**Issue by madgen** [digital-asset/ghcide#14]
I installed `hie-core` and it works from command line on a given file. I also installed `vim-lsp` to integrate with `neovim` and added the configuration line from the `README` in my `init.vim`, but when I try `:LspHover` on a symbol, I get `Retrieving hover not supported for haskell`. What do I do next?

**Comment by maralorn** [comment]
> ```
>       "initializationOptions": {
>         "languageServerHaskell": {
>           "hlintOn": true,
>           "maxNumberOfProblems": 10,
>           "completionSnippetsOn": true
>         }
>       }
>     },
> ```

I may be wrong, but arn‘t these options from the usage wih hie-wrapper as seen for example here: http://marco-lopes.com/articles/Vim-and-Haskell-in-2019/ ?

If yes that part of the config should probably be removed from the README. Also right now I am missing hlint, warnings and completions with coc + ghcide. Only errors work.

**Comment by ndmitchell** [comment]
HLint and completions aren't (yet) features of ghcide. Warnings should be there, but you may want to turn on certain warnings.

**Comment by maralorn** [comment]
Thanks for the explanation! I made a pull request for the config.

Is there a good channel to ask for problems with setup, which are probably not bugs?

**Comment by ndmitchell** [comment]
There seem to be a lot of Vim installation instructions at https://github.com/digital-asset/ghcide#using-with-vimneovim. If none of them are sufficient please send a patch.

My guess is 90% of issues are setup issues. I think we'll just treat them like normal bugs for now.
