### ISSUE TITLE
That’s a very good point, I’m not actually sure how you are supposed to handle this given the fact that `haskell-lsp` doesn’t allow you to set options from `onStartup`. I guess, for now we could probably just set `CodeActionOptionStatic True` which if I understand the spec correctly is always fine even if the client doesn’t specify it in its capabilities.

### ISSUE THREAD

**Issue by jacg** [digital-asset/ghcide#151]
That’s a very good point, I’m not actually sure how you are supposed to handle this given the fact that `haskell-lsp` doesn’t allow you to set options from `onStartup`. I guess, for now we could probably just set `CodeActionOptionStatic True` which if I understand the spec correctly is always fine even if the client doesn’t specify it in its capabilities.

_Originally posted by @cocreature in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjAzMDE3ODg0OnYy/pull_request_review_threads/discussion_

**Comment by jacg** [comment]
@cocreature Sorry, I accidentally created this issue when trying to get a link to the conversation, to use in a PR descritpion. It's a bloody ugly, and annoying title that shows up in completion suggestions. Could you use your admin rights to eliminate it, please?

Sorry for the noise.

**Comment by cocreature** [comment]
I can’t remove it completely but I’ve made the title shorter at least.

**Comment by jacg** [comment]
Thanks. That's much better, and perfectly tolerable, but it's a shame that https://help.github.com/en/articles/deleting-an-issue doesn't work.
