### ISSUE TITLE
Put ghcide on Hackage

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#16]
hie-bios is now on Hackage. Could we upload hie-core to Hackage too? It would make installation massively simpler. I have a room of people trying to install it, could that be done?

**Comment by cocreature** [comment]
I just uploaded `ghcide` to Hackage https://hackage.haskell.org/package/ghcide and deprecated the `hie-core` package. Given that we have #30 for the VSCode extension I’m closing this for now. I want things to stabilize a bit more before I move it to `stackage`.
