### ISSUE TITLE
--lsp hangs in nix-shell

### ISSUE THREAD

**Issue by willisplummer** [digital-asset/ghcide#160]
I've been running into an issue where it seems that `ghcide --lsp` has totally hung in a relatively small project that I've been setting up with nix

https://github.com/willisplummer/haskell-nix

It works if I run `ghcide` without the `--lsp` flag.

I'm at a loss about what's going wrong. It would be helpful if there was a verbose flag I could pass to get more info about what's happening, but I'd also really appreciate if anyone has any other ideas what I should be doing differently?

**Comment by cocreature** [comment]
Can you explain what exactly you are trying to do? `ghcide --lsp` is the command that your LSP client (e.g. VSCode) should be using. It isn’t supposed to be run in a terminal and if you do run it in a terminal it won’t print any output until you send it valid LSP commands.

**Comment by willisplummer** [comment]
Ah, sorry - I hadn't realized that. I've been attempting to get this working with vscode by setting the path to ghcide to `./ghcide` but I'm not currently getting any feedback when I edit a type signature to be incorrect and I thought that the lack of feedback when running `ghcide --lsp` was indicative of something.

I actually just identified the issue. Thanks!

**Comment by ndmitchell** [comment]
Should --lsp print a message to stderr to explain its starting a server and listening for messages? I think I've seen someone get confused before.

**Comment by cocreature** [comment]
Sounds like a good idea.
