### ISSUE TITLE
Weird errors (maybe package.yaml not read correctly)

### ISSUE THREAD

**Issue by anfelor** [digital-asset/ghcide#163]
While working on [anfelor/Naproche](https://github.com/anfelor/Naproche-SAD) in `vscode` `ghcide` has started to return lots of `Could not find module` and one `Illegal lambda case` error even though stack compiles without complaints. I suspect its due to the `package.yaml` file not being read again, when it changes; for example through `git pull` or `git checkout`. Unfortunately I don't know anymore when it started to do this and the errors stay when I go back to old commits of my code :(

**Comment by cocreature** [comment]
Do you have a `hie.yaml` file? If you use the stack cradle as described in `https://github.com/mpickering/hie-bios#explicit-configuration` then restarting `ghcide` should make it pick up changes from your `package.yaml` file.

**Comment by anfelor** [comment]
Yep, that works! It still forces me to restart my IDE when I use `git checkout` in the console, though.

**Comment by cocreature** [comment]
See #50 for automatically detecting changes to cabal files. Closing since it seems like a duplicate of that issue. Feel free to reopen if I misunderstood you.

**Comment by anfelor** [comment]
Actually, I just found out that it wasn't adding the `hie.yaml` that worked, but rather not using two projects in one workspace. So it seems like this is a problem of `vscode`.
