### ISSUE TITLE
Type errors not shown when using cabal

### ISSUE THREAD

**Issue by kosmikus** [digital-asset/ghcide#170]
Under certain circumstances that I have not yet been able to determine completely, ghcide seems to accept erroneous files without complaining when using a `cabal` cradle. (I cannot reproduce this with either direct or stack cradles.)

This seems to happen with both ghcide-0.0.3 from Hackage and the current master, built using ghc-8.6.5.

### To reproduce

1. Create a new directory `ghcide-test`.

2. Create a file `cabal.project`:
    ```
    packages: .
    ```

3. Create a file `ghcide-test.cabal`:
    ```
    name: ghcide-test
    version: 0.1
    build-type: Simple
    cabal-version: >= 1.2

    library
      default-language: Haskell2010
      hs-source-dirs: .
      build-depends:
        base
      exposed-modules:
        Foo
    ```

4. Create a file `Foo.hs`:
    ```haskell
    module Foo where

    x :: Int
    x = "foo"

    y :: Int
    y = _
    ```

5. Run `ghcide`.

This is the output I'm getting:
```
Starting ghcide (GHC v8.6)
/home/andres/repos/ghcide-test
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "/home/andres/repos/ghcide-test", cradleOptsProg = CradleAction: cabal}

[2/6] Converting Cradle to GHC session

[3/6] Initialising IDE session

[4/6] Finding interesting files
Found 1 files

[5/6] Setting interesting files
[DEBUG] Set files of interest to: [NormalizedFilePath "./Foo.hs"]
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)

[6/6] Loading interesting files
[DEBUG] Finishing shakeRun (took 0.00s, exception: thread killed)
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
[DEBUG] Finishing shakeRun (took 0.16s, completed)
Files that worked: 1
Files that failed: 0
Done
```

I would expect ghcide to report the errors. In the editor, no errors in `Foo.hs` are shown either.

---

Things seem to become better once I enable more warnings in `ghc-options` such as `-Wall`, `-Wdeferred-type-errors` and/or `-Wtyped-holes`.

I have the feeling that the output is somewhat non-deterministic even in such cases though, with not always the same errors being shown and occasionally the file still being accepted without errors being reported (but rarely). Could there be a race condition involved?

**Comment by kosmikus** [comment]
I think the problem is that in `typecheckModule`, `ghcide` sets a number of flags that turn various things into warnings, but does not ensure that these warnings are actually triggered.

For me, changing the definition of `demoteTEsToWarns` in `Development.IDE.Core.Compile` from
```
  demoteTEsToWarns :: DynFlags -> DynFlags
  demoteTEsToWarns = (`gopt_set` Opt_DeferTypeErrors)
                   . (`gopt_set` Opt_DeferTypedHoles)
                   . (`gopt_set` Opt_DeferOutOfScopeVariables)
```
to
```
  demoteTEsToWarns :: DynFlags -> DynFlags
  demoteTEsToWarns = (`wopt_set` Opt_WarnDeferredTypeErrors)
                   . (`wopt_set` Opt_WarnTypedHoles)
                   . (`wopt_set` Opt_WarnDeferredOutOfScopeVariables)
                   . (`gopt_set` Opt_DeferTypeErrors)
                   . (`gopt_set` Opt_DeferTypedHoles)
                   . (`gopt_set` Opt_DeferOutOfScopeVariables)
```
fixes the problem for me.

All three are needed and seem to be unset using a plain cabal cradle, whereas they do seem to be set by default using a direct cradle with no arguments. I'm not sure whether this means there's something strange with `hie-bios`.

**Comment by kosmikus** [comment]
After talking to @mpickering, it looks like `cabal-install` adds `-w` (disable all warnings) when being invoked with `-v0`, which is what `hie-bios` currently does. So my situation will be fixed via changes to `hie-bios`, and no action is urgently needed here.

There's still a more fundamental question whether `ghcide` should ensure these warnings are enabled when it starts deferring errors to warnings. It is very confusing to suddenly end up in a situation where certain errors are not reported at all.

I'm therefore going to leave this open, but feel free to close if you think the current behaviour of `ghcide` is ok.

**Comment by ndmitchell** [comment]
Thanks for tracking this down @kosmikus! I raised a PR based on it as https://github.com/digital-asset/ghcide/pull/172. I'd say hie-bios is definitely in error here, as it shouldn't cause non-user flags to appear, but ghcide shouldn't make things worse when it turns on warnings implicitly.

**Comment by cocreature** [comment]
Thanks for tracking this down. Closing since we merged @ndmitchell’s PR that enables these warnings.
