### ISSUE TITLE
Program error: Failed to load interface for ‘Data.DList’ There are files missing in the ‘dlist-0.8.0.7’ package,

### ISSUE THREAD

**Issue by shivamashtikar** [digital-asset/ghcide#194]
when I `import System.File.Glob` ghcide is throwing following error on vscode
```
Program error: Failed to load interface for ‘Data.DList’
There are files missing in the ‘dlist-0.8.0.7’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.typeche
```
and following on terminal
```
Step 6/6: Type checking the files
File:     ./src/File/FileStream.hs
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Program error: Failed to load interface for ‘Data.DList’
Files that failed:
  There are files missing in the ‘dlist-0.8.0.7’ package,
 * ./src/File/FileStream.hs
  try running 'ghc-pkg check'.
  Use -v to see a list of the files searched for.

Completed (2 files worked, 1 file failed)
```
I'm using `cabal+nix`

**Comment by cocreature** [comment]
Are you running `ghcide` from a nix shell? If so, maybe take a look at https://github.com/digital-asset/ghcide/blob/master/docs/Setup.md#issues-with-nix

**Comment by shivamashtikar** [comment]
Yes I'm running `ghcide` from nix shell. For vscode I'm using `direnv` to make `ghcide` work

**Comment by shivamashtikar** [comment]
It was woking with same dependencies on the other repo having. I latter moved to new project and borrowed the dependencies. Since then I'm facing this issue. At first I thought there was some problem with nix, but after debugging I found out that the problem origins form `ghcide` when I import Glob

**Comment by cocreature** [comment]
Could it be that you are using a different GHC version?

**Comment by shivamashtikar** [comment]
I built `ghcide` with the same version that I'm using in my project

**Comment by cocreature** [comment]
And you looked at the libdir fixes that I linked to above?

**Comment by cocreature** [comment]
Oh which cradle are you using? And have you installed all deps via nix or did you get some from cabal-install?

**Comment by shivamashtikar** [comment]
I have installed all dependencies using nix

**Comment by shivamashtikar** [comment]
default cradle
```
Step 3/6, Cradle 1/1: Implicit cradle for /home/shivam/Documents/transporter
Cradle {cradleRootDir = "/home/shivam/Documents/transporter", cradleOptsProg = CradleAction: default}
```

**Comment by cocreature** [comment]
Can you try the cabal cradle?

**Comment by shivamashtikar** [comment]
Can you please give one example of cabal cradle

**Comment by shivamashtikar** [comment]
using cabal cradle worked. I just had to add 
```
cradle: {cabal: {component: "project-name"}}
```
in `hie.yaml` file in projects root dir

@cocreature  Thanks for helping

**Comment by cocreature** [comment]
@shivamashtikar Great! I’ve documented the solution to this issue in https://github.com/digital-asset/ghcide/pull/195
