### ISSUE TITLE
Switch the import module finding order

### ISSUE THREAD

**Issue by jinwoo** [digital-asset/ghcide#204]
In https://github.com/digital-asset/ghcide/blob/master/src/Development/IDE/Import/FindImports.hs#L81-L82, we prefer the source files over the modules from the package database. But that causes problems in a multi-cradle environment. When module MA belongs to cradle CA and MA imports another module MB, which belongs to cradle CB, ghcide tries to interpret module MB because it is found as a source file. If the import dependency chain is deep, it significantly slows down ghcide and sometimes causes build errors because GHC options generated for module MA may not work for interpreting module MB.

We should prefer the package database in this case.

**Comment by cocreature** [comment]
The current behavior matches the behavior of `ghc` afaik and I don’t really want to diverge from that.

**Comment by cocreature** [comment]
A common way to avoid this issue is to use different source directories. That’s one reason why Haskell projects often have `app`, `src`, and `test`.

**Comment by jinwoo** [comment]
Makes sense. I suspect this problem is unique to our build system. I'm closing this now. We may have to patch ghcide's import module finding logic a little bit so that it doesn't search random locations in the file system but only the current set of target files.

Thanks, @cocreature !

**Comment by cocreature** [comment]
ghcide should never search random locations. It only searches the include dirs and relative to the module the import is from (the latter is mostly coming from DAML and will probably go away at some point).

**Comment by jinwoo** [comment]
Ah, sorry that's what I meant :)

And that doesn't work very well with our internal build system (basically bazel).
