### ISSUE TITLE
GHC sessions seem to leak

### ISSUE THREAD

**Issue by jinwoo** [digital-asset/ghcide#205]
In our environments, we have multiple cradles running under the same ghcide run. When I run ghcide from the command line, the result depends on the order of the files that I pass to ghcide.

E.g.
```sh
$ ghcide A.hs B.hs
```
runs fine without any errors. But
```sh
$ ghcide B.hs A.hs
```
gives errors for `A.hs`, which I don't see from actual builds.

In this example, `A.hs` and `B.hs` belong to different cradles.

It doesn't happen for any random pairs, and I'm not sure exactly in which condition this happens. But it definitely seems that there's some interference between GHC sessions.

**Comment by ndmitchell** [comment]
It isn't massively surprising that different GHC Sessions leak. I believe it's been cleaned up in each successive GHC version - what version are you running? Is there a reason you are mixing different cradles together?

**Comment by jinwoo** [comment]
We are using GHC 8.6.4 now.

Looking at this further, this seems to be a problem only when running ghcide from the command-line (i.e., in non-lsp mode). When using ghcide in an editor, I don't seem to have this problem. Ghcide gives such errors only when I run it against multiple files or against a directory.

The reason we mix multiple cradles is because of how we compile Haskell code. In our environment, each build target becomes one Haskell package and has a different set of build flags from other targets. Because ghcide's cradle corresponds to one GHC session (hence one set of build flags), we have to use multiple cradles (one for each build target).

**Comment by jinwoo** [comment]
This problem seems unique to our multi-cradle environment. And this is problematic only in the command-line mode (non-lsp mode).

The `grab` function creates sessions only for the files that are passed via the command line: https://github.com/digital-asset/ghcide/blob/master/exe/Main.hs#L113. So when a file imports another module that is not part of the given files and belongs to a different cradle, the build/typecheck may fail due to the difference in compile options (such as `-package-id`, `-package-db`, etc.).

I'll just create an internal patch for this problem. Closing.

**Comment by ndmitchell** [comment]
When you say leaking, do you mean leaking an unbounded number, or just that there are a number of them alive at the same time? I don't see how to throw one away, since you don't know when it will be useful.

What is your internal patch to fix it? Keen to take all generally useful patches upstream.

**Comment by jinwoo** [comment]
When I said "leaking", I didn't mean that sessions were not deleted. We used to get unexpected type errors sometimes when running ghcide against multiple files (or cradles) in command-line mode, and we initially thought that GHC sessions were not fully isolated and affected each other somehow.

But it turned out the problem was in the logic for finding imported modules. Because of how our build system (internal variant of bazel) works, the imported modules shouldn't be located from random places in the file system, but should be located from the dependencies that are specified in the build rules.

That was our internal patch. I don't think it helps external developers because the problem is unique to our build system (and because newer versions of hie-bios don't support bazel either).

**Comment by ndmitchell** [comment]
Ah, that makes sense - thanks for the clarification. Would be curious to know if you are able to use ghcide successfully, or if there are issues of scale/complexity that make it not work in your environment (if you're able to share).

**Comment by jinwoo** [comment]
ghcide works pretty well in our environment. Typically we have a lot of active cradles simultaneously because each build target becomes one cradle (and most build targets have only one source file) in our setup. But I don't think we have any scalability issues. Thanks for initiating and maintaining this project! It's very useful for us.

**Comment by ndmitchell** [comment]
FWIW, in a situation somewhat similar to you, I've written a script to generate hie.yaml files, and merge multiple small build targets into bigger cradles. We still have multiple cradles, but only a handful. That makes things like goto definition work better (so it seems). GHC will one day be able to support multiple editable packages in one session, and then things should require only one cradle ever.

**Comment by jinwoo** [comment]
Yeah, "go to definition" not working across cradles is a small annoyance in our case. I'm not sure how we can combine multiple build targets into one cradle because each build target has different GHC arguments and dependencies.

**Comment by ndmitchell** [comment]
Usually (but far from always) just shoving all the flags, dependencies and extensions together makes it continue to work. We have a plan to do something a bit like that in a future ghcide, where as long as everything has consistent dependencies (e.g. a monorepo or single Stackage snapshot) then we should be able to have one cradle with different flags. When we've done that, hopefully you'll be able to merge them more safely.

**Comment by jinwoo** [comment]
Oh, ok. We want to avoid combining arguments/dependencies from multiple targets because it may cause subtle bugs or sometimes circular dependencies. If ghcide can support having one cradle with different flags, it'd be great. Having many cradles, however, doesn't seem to be an issue for us.
