### ISSUE TITLE
ghcide needs -fexternal-interpreter?

### ISSUE THREAD

**Issue by roberth** [digital-asset/ghcide#206]
We're getting this error in ghcide.

    ghcide: ghcide: this operation requires -fexternal-interpreter

https://github.com/hercules-ci/ghcide-nix/pull/18#issuecomment-555127101

Shouldn't ghcide hardcode this flag if it depends on it, or how do we deal with this?

**Comment by ndmitchell** [comment]
I think `-fexternal-interpreter` implies other things that we don't do, so I'm not sure it's as simple as adding the flag in.

**Comment by cocreature** [comment]
To add a bit more: We definitely don’t always depend on `-fexternal-interpreter`. This sounds like something that might be caused by a project using template haskell?

**Comment by roberth** [comment]
I did some research earlier today and it turns out it can also be thrown when ghc is compiled without ghc support, which seems to be [the case](https://github.com/input-output-hk/haskell.nix/issues/313) with haskell.nix at the moment.
As far as I can tell, `-fexternal-interpreter` is only needed for cross-compilation, ghcjs and those kinds of things, whereas my setup  did not have any of that.
So this does not seem to be a problem in the ghcide project.
