### ISSUE TITLE
Module not found when importing Data.Morpheus

### ISSUE THREAD

**Issue by cjduncana** [digital-asset/ghcide#208]
After creating a new project using the `scotty-hello-world` template, I added the `morpheus-graphql` package, yet when I import `Data.Morpheus` it complains it can’t find the module.

``` haskell
import Data.Morpheus
-- Could not find module ‘Data.Morpheus’
-- It is not a module in the current program, or in any known package.
```
I've added the package in both the `*.cabal` and `stack.yaml` files. I've built the program using `stack build` and restarted VSCode.

The same day, I started another project with the same template but using the `graphql-api` package. I'm in the middle of exploring both packages. I got no problems there.

**Comment by ndmitchell** [comment]
What happens if you run `ghcide` from the command line in the relevant directory? What does it say?

**Comment by cjduncana** [comment]
It shows other errors that I have lower in the file. The important thing is that it doesn't show the error I posted in the original post.

**Comment by cocreature** [comment]
Do you have a `hie.yaml` file? If not, I would suggest to add one and specify the stack cradle.

**Comment by cjduncana** [comment]
That was it. 🙌Thank you very much.
