### ISSUE TITLE
Please release version compatible with haskell-lsp-0.18

### ISSUE THREAD

**Issue by turion** [digital-asset/ghcide#234]
I want to fix ghcide on NixOS (https://github.com/NixOS/nixpkgs/pull/75449). My goal is to make the installation of ghcide on NixOS seamless. The best way forward would be to have a release of `ghcide` that is compatible with an up to date version of `haskell-lsp`, at least `haskell-lsp-0.17` (but `0.18` is great, too). On `master`, this is already there, so the only thing missing is a hackage release.

**Comment by fendor** [comment]
There is probably soon another release of haskell-lsp. So maybe it makes sense to wait for that release?

**Comment by cocreature** [comment]
Given that my plan to wait for a new `hie-bios` release before making a new `ghcide` release hasn’t worked out well since that took way longer than I expected it to, I’d rather make a new release this week and then another one if there is a new `haskell-lsp` release.

**Comment by turion** [comment]
In my experience, it's always a hassle to try and keep releases between different packages aligned.

**Comment by ocharles** [comment]
If there's a meta discussion about release cadence, I would recommend taking a book out of Dhall's book and just have a predictable release cycle. You already have an excellent merge process (afaict, everything is a PR, there's no working on `master`), so you should always be in a pretty releasable state. Gabriel wrote his thoughts up in http://www.haskellforall.com/2019/05/release-early-and-often.html, if you haven't seen the argument before.

**Comment by alanz** [comment]
Its one of the reasons I have been aiming for a monthly "release" of hie, just keep things moving along.

**Comment by cocreature** [comment]
I’ve just released 0.0.5 which supports the latest `haskell-lsp`.

**Comment by turion** [comment]
Awesome, thanks :) I'll make sure it works properly in NixOS from here.
