### ISSUE TITLE
Performance regression 

### ISSUE THREAD

**Issue by domenkozar** [digital-asset/ghcide#240]
Comparing on our codebase of ~140 modules, typechecking (almost top-level) file `Server.hs`:

- 50e35f0e98241b9cbe0f716ee16c5c5871599ae1 (0.0.3): 6s
- 18955c32b81d78e80fed96b9865a8c4a75d92557 (0.0.4): ~13s

Also, should typechecking be incremental?

**Comment by cocreature** [comment]
typechecking is incremental on a per-module basis. What exactly are you measuring to get those numbers? Is your project public so we can reproduce this? How does `0.0.5` do?

**Comment by domenkozar** [comment]
> typechecking is incremental on a per-module basis.

It's strange to me that there's 22k things to typecheck in 13s.

> What exactly are you measuring to get those numbers? 

I'm using VSCode and saving a file, then watching ghcide log produce `Finishing shakeRun` log entry.

>  Is your project public so we can reproduce this?

No, but I've tried on https://github.com/hercules-ci/hercules-ci-agent/tree/master/hercules-ci-api-agent and I get 8s for ~10k steps saving `Hercules.Agent.Build`.

> How does 0.0.5 do?

About the same as 0.0.4

**Comment by cocreature** [comment]
> It's strange to me that there's 22k things to typecheck in 13s.

The number is the number of shake tasks and it always shows the total number of steps even if they were skipped because we already had up2date results for some of them so the fact that the number is high doesn’t tell you much.

What time to do you get on `0.0.3` on your public project? Also are you experiencing a significant performance regression or is the number in the log just going up? iirc we refactored that part a bit to fix some bugs and I wouldn’t be surprised if the number now displays something slightly different.

**Comment by domenkozar** [comment]
> What time to do you get on 0.0.3 on your public project?

~2s

> Also are you experiencing a significant performance regression or is the number in the log just going up?

I'm only observing the time it takes to complete shakeRun. In 0.0.3 there's no progress reported so I can't say how many steps it took.

**Comment by domenkozar** [comment]
> The number is the number of shake tasks and it always shows the total number of steps even if they were skipped because we already had up2date results for some of them so the fact that the number is high doesn’t tell you much.

This is by far not a scientific measurement, but I'd say it does slow down at the very end. But getting through the first 90% is takes quite  a few seconds. Maybe progress reporting makes it slow?

**Comment by cocreature** [comment]
Progress reporting is done on a separate thread and it’s throttled to update only every 0.1s so I would be surprised if that’s a bottleneck. Our best option is probably to bisect to figure out what exactly introduced the slowdown so we can see if it’s an actual performance regression or if it’s simply a case of the measurements shown in the log having changed.

**Comment by ndmitchell** [comment]
I think this does bring up the lack of performance tests - it's a fairly subtle system to not make performance regressions, and at the moment, they probably won't be spotted. Maybe that needs its own ticket?

**Comment by cocreature** [comment]
I’ve opened #242 to track the missing performance tests.

**Comment by ndmitchell** [comment]
Is the performance still regressed?

**Comment by domenkozar** [comment]
It's very fast now.
