### ISSUE TITLE
Hover does not work for type constructors

### ISSUE THREAD

**Issue by jacg** [digital-asset/ghcide#248]
... as demonstrated by the test titled *type constructor*.

**Comment by jacg** [comment]
I think I understand why it is not working, and how to fix it. But I don't know what to display in the hover message. What should the hover info look like for types?

**Comment by jacg** [comment]
> What should the hover info look like for types?

For values we have
````
name
    :: type
Defined at/in ...
````
so for types, classes and type variables maybe it should be
````
Class/Type/Typevar: name
    :: kind
Defined at/in ...
````
?

Not sure how easy it will be to get the kind.

**Comment by ndmitchell** [comment]
I think any information (where it is defined for instance) is an improvement. If you can get the kind that would be nice, but I wouldn't try too hard to find it.

**Comment by kosmikus** [comment]
I would really appreciate kind information to be printed, but I don't know how difficult it is. I had tried to add this some months ago, and it wasn't immediately clear to me how.
