### ISSUE TITLE
Update to hie-bios 0.3

### ISSUE THREAD

**Issue by mpickering** [digital-asset/ghcide#255]
Yesterday I released `hie-bios-0.3` which includes quite a number of improvements over the previous release. `ghcide` will need to be updated for the API changes and could take advantage of some new features such as reprorting progress when trying to load a cradle.

**Comment by cocreature** [comment]
https://github.com/digital-asset/ghcide/pull/257 at least makes sure that things compile. Taking advantage of new features will take more time but we can probably at least benefit from some bugfixes.

**Comment by cocreature** [comment]
fixed in #257 

We have #258 for the non-cradle and #113 to track the missing features.
