### ISSUE TITLE
Polymorphic local bindings quickfix + NoMonomorphismRestriction / NoMonoLocalBinds

### ISSUE THREAD

**Issue by amesgen** [digital-asset/ghcide#265]
Since #232, ghcide shows quick fixes (underlined in blue for me in emacs-lsp) for polymorphic local bindings. IMHO it would be a good idea to hide them by default if NoMonomorphismRestriction and NoMonoLocalBinds are enabled.

**Comment by cocreature** [comment]
I completely agree, see #263

**Comment by cocreature** [comment]
#263 has been merged so this is fixed
