### ISSUE TITLE
Record-dot-preprocessor does not work with ghcide on Windows

### ISSUE THREAD

**Issue by pkapustin** [digital-asset/ghcide#294]
Message:  ghcide: could not execute: record-dot-preprocessor

Everything works fine on Linux.
The projects builds fine with record-dot-preprocessor on Windows, but not in ghcide.

**Comment by ndmitchell** [comment]
Is record-dot-preprocessor on your PATH? It works for me on Windows

**Comment by pkapustin** [comment]
It wasn't, sorry :)
Works great now!

**Comment by ndmitchell** [comment]
I guess stack puts more on the PATH. I guess hie-bios should have some way of saying what got put on the PATH? Cc @mpickering. With that info it should be quite easy to fix.
