### ISSUE TITLE
performance degradation after upgrade to haskell-lsp 0.19

### ISSUE THREAD

**Issue by pepeiborra** [digital-asset/ghcide#298]
I've noticed a hover performance degradation in head, and bisected it to this change. Hover takes twice as long for me.

_Originally posted by @pepeiborra in https://github.com/digital-asset/ghcide/pull/254#issuecomment-569924242_

**Comment by cocreature** [comment]
In a lot of cases, hover is bottlenecked on checking if files have changed see #101. IIRC the latest `haskell-lsp` release has changed how the VFS is accessed (iirc it now goes via STM) so my guess would be that this is what is causing the slowdown but it would be good to bisect through the `haskell-lsp` changes to verify that.

**Comment by pepeiborra** [comment]
@cocreature have you seen my Shake profiles in the original comment?

**Comment by cocreature** [comment]
Ah I missed those, thanks for pointing that out. That seems to confirm my suspicion that VFS lookups got slower.

**Comment by pepeiborra** [comment]
Bad hover performance is a major problem for lsp-emacs, which seems to send a hover request for every character typed, and then on a timer even when not typing. VSCode does not do this.
