### ISSUE TITLE
Add VSCode extension to the marketplace

### ISSUE THREAD

**Issue by domenkozar** [digital-asset/ghcide#30]

**Comment by mpickering** [comment]
Any progress with this?

**Comment by ndmitchell** [comment]
See #90 - it seems there's a lot of variability in what works and what doesn't when installing by hand.

**Comment by cocreature** [comment]
Hoping to get around to it next week.

**Comment by cocreature** [comment]
The extension is now in the marketplace https://marketplace.visualstudio.com/items?itemName=DigitalAssetHoldingsLLC.ghcide

**Comment by domenkozar** [comment]
Needs changes to readme.
