### ISSUE TITLE
Support direnv natively in VSCode plugin

### ISSUE THREAD

**Issue by fiadliel** [digital-asset/ghcide#301]
Hi there,
there has been some discussion before about what workarounds are needed to support nix environments. One thing which may help could be to add direnv support (to add nix environment variables).

While there is already a direnv plugin for VSCode, this modifies global variables, and so doesn't seem like good hygiene; also, I'm not sure if this would then preclude multi-root workspace support, which would need different environment variables for each ghcide instance. Also, it doesn't restart the LanguageClient (e.g. if the environment changes).

Would you be interested in adding direnv support directly to the ghcide VSCode plugin? This allows the invoking of the LanguageClient to be done with an explicit environment.

I've written an example of how this could work (excuse my rusty JS) at https://github.com/fiadliel/ghcide/blob/643453f73c050cf2332f17c9794bee3c1ea73ef5/extension/src/extension.ts

A nice side-effect of this is that the build itself can define which version of ghcide is in the path, and can add other binaries like hlint/ormolu/etc. that may be needed.

**Comment by ocharles** [comment]
It's maybe not quite related, but I use ghcide with direnv and Emacs, and don't see any need to change anything in ghcide itself. My setup is:

* A .envrc which uses Lorri to set up `PATH`
* Our Nix shell itself has `ghcide`, so when I enter that directory and type `ghcide`, it will run the `ghcide` from that Nix shell.
* A `shellHook` re-exporting some Nix-specific GHC environment variables.
* Emacs has `direnv-mode`, which means whenever I enter a file in a directory that is a descendant of my `.envrc` file, Emacs calls to direnv to set up the environment variables.
* Emacs also has Projectile and lsp-mode. lsp-mode works with projectile to find the project root and spawn a language server process - in this case ghcide in the root directory of my project.
* Projectile/lsp-mode keep track of which files belong to projects so only one ghcide process is created.

**Comment by domenkozar** [comment]
There's more discussion in https://github.com/microsoft/vscode/issues/46696 to support Nix and initializing the VSCode extensions, I think that should be out of scope for ghcide.

**Comment by cocreature** [comment]
I agree that this isn’t something that we should try to tackle in `ghcide`. Setting up the environment is something that every developer tool needs to do and if every tool reinvents this, we are just going to end up with a mess of different ways to set things up that are incompatible or behave subtly different. If the VSCode direnv plugin doesn’t work properly, that should be fixed instead of trying t oreplicate this in the ghcide VSCode extension.
