### ISSUE TITLE
Trigger completion after dot?

### ISSUE THREAD

**Issue by serras** [digital-asset/ghcide#312]
LSP allows a server to publicize that completions should be requested after some characters. Many languages define `.` as this character, because you would usually obtain a list of the fields and methods inside the corresponding object.

The question is: should we enable this behavior in `ghcide`? On the one hand, it's quite interesting to write `Data.Text.` (or a qualified version) and get every possible function in that module. On the other hand, `(.)` is a function in `Prelude`, and getting completions when you are writing point-free code could be confusing.

**Comment by ndmitchell** [comment]
Presumably you could enable completions after `.`, but if someone writes `map f .` then the completions would be the empty list.

Also, would be great if completions worked with [RecordDotSyntax](https://github.com/ghc-proposals/ghc-proposals/pull/282) :)

**Comment by serras** [comment]
Right, I would need to check the behavior. Maybe what we get instead is the whole set of things in scope.

**Comment by aherrmann-da** [comment]
https://github.com/digital-asset/ghcide/pull/313 triggers completion after dot. `RecordDotSyntax` is not addressed, yet.
