### ISSUE TITLE
Crash without explicit hie.yaml if the user has no read permissions for a parent directory

### ISSUE THREAD

**Issue by mbg** [digital-asset/ghcide#314]
I have an issue with `ghcide` on a shared system where users don't have read permissions for a parent directory of their home directories which results in the following crash during step 3 of the startup:

```
Step 3/6, Cradle 1/1: Implicit cradle for /[directory without read permissions]/[username]/[project]
ghcide: /[directory without read permissions]: getDirectoryContents:openDirStream: permission denied (Permission denied)
```

This happens with `ghcide` compiled using the current HEAD (a0aa013e3362d6ae0a963639d7845ec9990350fe).

A workaround is to have an explicit `hie.yaml` file in the current directory.

**Comment by cocreature** [comment]
That looks like it’s probably an issue in the logic in https://github.com/mpickering/hie-bios when locating the `hie.yaml` file. It would be great if you could open an issue in that repo.

**Comment by mbg** [comment]
Thanks for the quick response! I have opened an issue in the `hie-bios` repo for this now (see reference above).

**Comment by ndmitchell** [comment]
Fixed upstream, so this can be closed now.

**Comment by cocreature** [comment]
Thanks!
