### ISSUE TITLE
Errors with GSL

### ISSUE THREAD

**Issue by alex404** [digital-asset/ghcide#323]
Hello, I maintain a large optimization library, and I can't get ghcide to run on it. If I go to the root dir of one of the packages and run it I get

```
Step 1/6: Finding files to test in /home/alex404/code/goal/core
Found 13 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /home/alex404/code/goal/core
Cradle {cradleRootDir = "/home/alex404/code/goal", cradleOptsProg = CradleAction: stack}

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: <command line>: can't load .so/.DLL for: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libgsl.so (/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libgsl.so: undefined symbol: cblas_ctrmv)
```

Sorry if this is just a arch linux side linking problem, but I have both cblas and gsl installed, and I've never had a problem like this anywhere else (including with my code). I'd certainly like to use ghcide so any tips would be much appreciated.

**Comment by ndmitchell** [comment]
It seems that function is in LAPACK. How are you pointing at LAPACK normally? Have you had to list it anywhere in your Stack/Cabal files?

**Comment by alex404** [comment]
Sorry I don't have much experience resolving linking issues. I have lapack installed as a normal Arch package as well (I use openblas for providing BLAS routines). All my interfacing with lapack and openblas is done through hmatrix, so if there are linking issues that it resolves internally I wouldn't know about it.

The cabal file for hmatrix is [here](https://hackage.haskell.org/package/hmatrix-0.20.0.0/hmatrix.cabal), but I don't see anything unusual.

Thanks for your fast response!

**Comment by ndmitchell** [comment]
I guess Stack must adjust your library path or put something as a linker flag. How it decides to do that, and what it decides to do, I have no idea... Let's see if anyone else does know.

**Comment by pepeiborra** [comment]
@alex404 this is a hie-bios question, see this comment in the README:
```
The ghcide executable mostly relies on hie-bios to do the difficult work of setting up your GHC environment. If it doesn't work, see the hie-bios manual to get it working. My default fallback is to figure it out by hand and create a direct style hie.yaml listing the command line arguments to load the project.
```
It might be as simple as going for a Cabal cradle.

**Comment by cocreature** [comment]
Does `stack ghci y<ourcomponenthere>` work? If `stack ghci` works but `ghcide` doesn’t chances are that it might be a bug in `ghcide` itself. We do a lot of stuff ourselves instead of leaving it to the GHC API so I wouldn’t be surprised if we messed up something somewhere. That said, it’s still worth trying a cabal cradle.

**Comment by alex404** [comment]
Stack ghci works fine (as does ghcid). When I have a moment I'll look into the Cable cradle, although it's been a while since I built my packages with cabal so that may take a bit of work. I'll report back when I do.

Thanks again everyone.

**Comment by alex404** [comment]
Okay, so I built the package with cabal and ghcide does indeed work in this case.

**Comment by ndmitchell** [comment]
I can't remember if ghcide spits out the flags it gets from hie bios, or puts them into a log. If so, seeing both sets of flags should tell us where the bug is.

**Comment by ndmitchell** [comment]
Seems ghcide doesn't spit out the super useful information. I suggest we add a feature where `ghcide` also writes out `ghcide.log` which has absolutely all the possible information we might be interested in. Then we could just diff the two and find out why stack fails but cabal works.

**Comment by alex404** [comment]
I'll certainly be happy to test it out on my case if you implement such a feature.

**Comment by alex404** [comment]
Hi there, i tested out my project with ghcide 0.2 and it seems to work like a charm! So whatever you did, thanks :)
