### ISSUE TITLE
Info on hover gets rendered differently in v0.0.6

### ISSUE THREAD

**Issue by moodmosaic** [digital-asset/ghcide#336]
There's a difference between <= 0.0.5 and == 0.0.6 in the way hovers are rendered. There's now an extra `<hr>` added, and type signature is placed separately, after `<hr>`.

[tags/v0.0.5](https://github.com/digital-asset/ghcide/tree/v0.0.5)

![image](https://user-images.githubusercontent.com/287532/72797099-cd68ea80-3c40-11ea-94cb-9321c4c0855d.png)

[tags/v0.0.6](https://github.com/digital-asset/ghcide/tree/v0.0.6)

![image](https://user-images.githubusercontent.com/287532/72797011-9c88b580-3c40-11ea-939f-d554bb3805ac.png)

Not necessarily a big deal, but I thought I should ask whether this change was intentional and if it was part of the https://github.com/digital-asset/ghcide/pull/260 refactoring.

**Comment by ndmitchell** [comment]
FWIW, I prefer the first...

**Comment by cocreature** [comment]
I don’t really care about which one we use so happy to accept a PR to change it back. In fact, I think https://github.com/digital-asset/ghcide/pull/317 might already have changed it back.

**Comment by moodmosaic** [comment]
Yep, indeed :+1: I've just pulled the latest (2f5d0d3e69abb5f321bf28b1049ae7a7fc9f619e) and it's fixed. In fact, it looks even better now. :tada: 

![image](https://user-images.githubusercontent.com/287532/72815130-76760c00-3c66-11ea-86e1-cb146ea26a58.png)
