### ISSUE TITLE
Completions are missing `do`

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#347]
When starting a file, and writing `main = do`, I get completions for `drop` etc. I suggest that keywords should be available as completions always. Particularly problematic because after `do` I often want a newline, but in this context enter inserts the word `drop`.

![image](https://user-images.githubusercontent.com/1651197/73067600-0dc6a380-3ea1-11ea-9482-971f1fc7218b.png)

**Comment by fendor** [comment]
Issue in haskell ide engine: https://github.com/haskell/haskell-ide-engine/issues/953

**Comment by ocharles** [comment]
This seems odd to me. Do other languages do this? E.g., if you write C#, does `cla` suggest `class`?

**Comment by cocreature** [comment]
The linked issue explains why this is less of an issue in other languages: In something like C# completions are mostly triggered after a `.` and you only get relevant completions. Whereas in Haskell we don’t have that clear indicator (except for qualified definitions) so you end up completing in a context where `do` could be valid.

**Comment by ndmitchell** [comment]
That's the state of IDE completion as it was a decade ago. In C# you're always completing, and yes, it does complete class - but probably into a snippet that contains the braces and a highlighted name too.
