### ISSUE TITLE
Completions should show the types

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#348]
When using completion support as a substitute for docs (which is how I do it in every other language), it's really useful to know the types. In this instance I want either `vector` or `vectorOf`, but I can't remember if vector takes an `Int` for the length or not. Having that information in addition to the module name would be super helpful.

![image](https://user-images.githubusercontent.com/1651197/73067752-67c76900-3ea1-11ea-9a11-8ca8c9c11986.png)

**Comment by fendor** [comment]
Since you are using the same completions as Haskell IDE Engine, shouldnt this already be the case? At least in HIE, there are types in completions. 

Maybe it is a bug?

**Comment by cocreature** [comment]
In HIE the type information mostly comes when resolving completion items and we don’t handle that so far. We only handle the actual completion request.

**Comment by serras** [comment]
Since https://github.com/digital-asset/ghcide/commit/a0aa013e3362d6ae0a963639d7845ec9990350fe the completions should show the type information (and docs) alongside the module. Can you reproduce this using `master`?

**Comment by serras** [comment]
Although most of the code is derived from HIE, the type information in `ghcide` is sent along the completion request, instead of using resolvers. But in any case, the information should be there.

**Comment by ndmitchell** [comment]
They now do, and they're awesome. I was running an old version.
