### ISSUE TITLE
the files generated by c2hs/cabal are not taken into account

### ISSUE THREAD

**Issue by teto** [digital-asset/ghcide#374]
I use c2hs to convert some C headers to haskell code (ffi).
cabal properly generates the files in a dist-newstyle/build subfolder and hie has no problem with it (once cabal has generated them). c2hs is required via https://github.com/teto/mptcp-pm/blob/master/mptcp-pm.cabal#L61 .

Here is a partial log from running ghcide.
```

Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Net.SockDiag.Constants’
  It is not a module in the current program, or in any known package.
File:     hs/daemon.hs
Hidden:   no
Range:    69:7-69:29
Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Net.SockDiag.Constants’
  It is not a module in the current program, or in any known package.
File:     hs/daemon.hs
Hidden:   no
Range:    70:7-70:24
Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Net.Tcp.Constants’
  It is not a module in the current program, or in any known package.
File:     hs/daemon.hs
Hidden:   no
Range:    71:7-71:26
Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Net.Mptcp.Constants’
  It is not a module in the current program, or in any known package.
Files that failed:
 * ./Net/Mptcp.hs
 * ./Net/SockDiag.hs
 * ./Net/Mptcp/PathManager.hs
 * ./Net/Mptcp/PathManager/Default.hs
 * ./hs/daemon.hs
 * ./hs/monitor.hs
 * ./hs/test.hs
 * ./test/Main.hs


Completed (2 files worked, 8 files failed)
```
How can I work around that ? is it because ghcide relies on shake and not cabal ?

**Comment by ndmitchell** [comment]
Most likely hie-bios has failed to put a path on the include directory. Do you have a `hie.yaml` file? If not, can you try creating one? See https://github.com/mpickering/hie-bios#explicit-configuration

Ghcide uses Cabal/Stack to get the environment, and Shake is an internal detail, so it's not that.

**Comment by teto** [comment]
I've added the following hie.yaml 
`cradle: {cabal: {component: "lib:haskell-ide-engine"}}` as per your link
but running ghcide gives
```
ghcide version: 0.0.6 (GHC: 8.6.5) (PATH: /nix/store/90z972r9125mhhm551w03q66y9kpvhyj-ghcide-0.0.6-exe-ghcide/bin/ghcide)
Ghcide setup tester in /home/teto/mptcp-pm.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /home/teto/mptcp-pm
Found 10 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading ./hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling cabal","","cabal: Internal error in target matching. It should always be possible to find\na syntax that's sufficiently qualified to give an unambiguous match. However\nwhen matching 'lib:haskell-ide-engine' we found lib:haskell-ide-engine\n(unknown-component) which does not have an unambiguous syntax. The possible\nsyntax and the targets they match are as follows:\n'lib:haskell-ide-engine' which matches lib:haskell-ide-engine\n(unknown-component), :pkg:lib:lib:lib:file:haskell-ide-engine (unknown-file)\n\n",""]
```
I am using NixOS and I have tried using as buildinputs both ghcide/haskell-ide-engine and only ghcide with the same result.

**Comment by ndmitchell** [comment]
You need to make it `lib:your-project-name-goes-here`. The error message isn't very good though, which is a bit of a shame, but I think is Cabal's fault.

**Comment by teto** [comment]
is there a documentation that specifies the syntax ? I guessed that I should use `exe:mptcp-pm` and it seems to work but thats a compelte guess.

**Comment by cocreature** [comment]
https://cabal.readthedocs.io/en/latest/nix-local-build.html#cabal-v2-build documents the target syntax for cabal. It’s nothing specific to `ghcide`. We just pass this on to `cabal v2-repl`.

**Comment by teto** [comment]
thanks. problem fixed.
