### ISSUE TITLE
ghcide: panic! dynamic linker not initialised

### ISSUE THREAD

**Issue by sebeaumont** [digital-asset/ghcide#38]
In VisualStudio code using the ghcide plugin I get this problem at startup
```
ghcide: panic! (the 'impossible' happened)
  (GHC version 8.6.5 for x86_64-apple-darwin):
	Dynamic linker not initialised

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```
Looking at the exe/Main.hs the version I am using was built against the head two days ago and 
this line seems to be present
```
    initDynLinker env
```
The problem seems to correct itself after a while -- maybe ```ghcide --lsp``` server re-starts itself... any pointers? Could there be multiple copies of ghcide involved? How does this all work if there are different versions of ghc in use in projects? 

ghcide runs ok in the (only) project at issue here. I'll see if I can track this down a bit.

**Comment by sebeaumont** [comment]
That code in GHC looks horrific... but it seems like in 8.8 all threads will synchronise on the state of the dynamic linker and I guess this issue has all the hallmarks of just the non-determinism one would expect from such a bug. It also points to the observation that the GHC compiler was never intended to be used as it now is. I bet this is fraught with problems... especially memory management of all that horrible state. You guys deserve medals if you can make this work for an ide.

**Comment by sebeaumont** [comment]
I guess we can close this as an "upstream" problem. ;-)

**Comment by cocreature** [comment]
Not entirely sure it’s an upstream problem simply because I tend to blame my own code first but if it isn’t it’s probably a duplicate of #28 so we can close it either way :slightly_smiling_face: If we still encounter it with 8.8 it probably deserves a deeper investigation.
