### ISSUE TITLE
Progress cancellation sometimes gets lost

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#381]
I had this happen a lot during the weekend (on my too slow for words laptop), and it's just happened on my desktop. I get the progress stuck at nearly complete - which I think is actually the progress completing but failing to send the progress completion message. As yet I have no way to reproduce. Looking at the code, either Shake fails to kill the thread, or killing the thread fails to send the message, or interleaving/VSCode is at fault.

**Comment by ndmitchell** [comment]
I added printing of start and stop messages. Indeed, it sometimes gets lost. Out of 22 progress notifications (while doing random dev work), 3 were lost. A few traces:

```
("PROGRESS Start",ProgressTextToken "8")
[DEBUG] Cancelled request IdInt 19
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
[DEBUG] Finishing shakeRun (took 0.00s, exception: AsyncCancelled)
("PROGRESS Start",ProgressTextToken "9")
```

```
("PROGRESS Start",ProgressTextToken "13")
[DEBUG] Cancelled request IdInt 36
[DEBUG] Cancelled request IdInt 37
[DEBUG] Cancelled request IdInt 38
[DEBUG] Finishing shakeRun (took 0.00s, exception: AsyncCancelled)
[DEBUG] Cancelled request IdInt 39
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
[INFO] Modified text document: f("PROGRESS Start",ProgressTextToken "14")
```

There is no `PROGRESS Stop` message. They all have an AsyncCancelled in the middle. I am not sure if that is the only case where they get lost, or if all cancellations lead to lost progress stop. The trace didn't show any obvious AsyncCancel where the stop did get sent, but some were ambiguously close due to possible overlapping input.

Next step is to test in isolation that Shake cancels the progress even if the main thread is cancelled, probably as a Shake test.

**Comment by ndmitchell** [comment]
This is a Shake bug which I've replicated outside of ghcide. Hopefully fixed in the next Shake release.

**Comment by cocreature** [comment]
Awesome, looking forward to that!

**Comment by ndmitchell** [comment]
The fix is in https://github.com/ndmitchell/shake/commit/5d991fee03f63020a5f32531b3ffe559b94d2272. The allocate thread cancels the thread, which involves read/writing a Var, and then waiting on a Barrier. Both those things are interruptible, so switching over to an uninterruptibleMask means they get to finish.

@cocreature would appreciate a second set of reasoning on that patch. If you're happy with it, I'll push out a release.

**Comment by ndmitchell** [comment]
Thanks for the comments on that patch. Fixed in Shake 0.18.5. I'll send in an upgrade to that, but it conflicts with #379 and #392 - are those two likely to get merged? If so, I'll wait and then send the upgrade.

**Comment by cocreature** [comment]
In principle I like both #379 and #392 but I’m somewhat hesitant to merge them now while progress reporting still seems to be a bit fragile since they both make it harder to debug. Maybe a good time to add a `--debug` flag which keeps the existing behavior?

**Comment by ndmitchell** [comment]
With the Shake upgrade and those two patches, progress reporting is rock solid for me. Once that's all in, if there are any further problems, I'm happy to investigate, including adding new debug flags - but my hope is that it's no longer necessary.

**Comment by domenkozar** [comment]
can be closed
