### ISSUE TITLE
Add restart command

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#389]
The Rust IDE provides a VS Code action to restart the IDE server - which lets you both experiment and work around bugs quickly without restarting the entire IDE. Would be super useful to have in the extension.

**Comment by fendor** [comment]
Maybe interesting: https://github.com/alanz/vscode-hie-server/pull/191

**Comment by cocreature** [comment]
Doesn’t `Control-Shift-P -> Reload Window` already achieve that?

**Comment by ocharles** [comment]
This seems like a very VS code specific feature. For those of us in Emacs, we can already do `lsp-restart` to restart `ghcide`.

**Comment by ndmitchell** [comment]
@cocreature reload let's you do it and more - too much more - clearing editor context, active searches, terminal windows and the like. It is entirely a vs code feature and may well end up exclusively in the TypeScript per of the project.

**Comment by cocreature** [comment]
If we get to the point that the fact that `reload window`  resets too much becomes a problem, I think we have much bigger problem. This should be an escape hatch that you basically never have to use so I don’t think we should rather fix whatever causes people to invoke it then spend time on making the restart experience nicer.

**Comment by ndmitchell** [comment]
We're at that point already. See #381. What happens when I upgrade stack. Or install something in my global package dB. Or upgrade ghcide. I've had all those happen yesterday. Rust is way more stable as an IDE and even there it's not uncommon to need to unstick it. I agree we should minimise the issues, and fix most of them, but not having the easy fix just hurts.

**Comment by cocreature** [comment]
Fair, I guess adding some logic for restarts to the VSCode extension shouldn’t be too hard.

**Comment by ndmitchell** [comment]
VSCode added a "Restart Extension Host" command which restarts all extensions, but for my use cases, is close enough to what I want here. My desire for this feature has gone, so closing this ticket (but if anyone else with a different editor feels it would be useful please reopen).
