### ISSUE TITLE
stack repl not working when using ghcide

### ISSUE THREAD

**Issue by kwaleko** [digital-asset/ghcide#390]
I am trying to use it on emacs, however, it create a file with the name of the file am working with adding to it "_Flymake.hs" which is stopping `stack repl` or `stack ghci`  giving me an error ` module ‘main:Lib’ is defined in multiple files: Lib_flymake.hs
                                                    Lib.hs`

**Comment by alanz** [comment]
customize `lsp-prefer-flymake` to be "Prefer lsp-ui", or "prefer neither".

You basically have to disable flymake.

**Comment by ocharles** [comment]
As Alan said, disable flymake and instead enable fly_check_

**Comment by kwaleko** [comment]
@alanz @ocharles  Thank you, basically this is what I have updated and my `use-package` look like this
`(use-package lsp-mode
    :ensure t
    :custom 
    (lsp-prefer-flymake nil)
    (lsp-prefer_fly_check t)
    :hook (haskell-mode . lsp)
    :commands lsp)`

am I doing the correct thing here? alsoI have notice that no warning are shown anymore in the editor, is that all or I have lost sth else?
