### ISSUE TITLE
What should I do when ghcide gets stuck?

### ISSUE THREAD

**Issue by ocharles** [digital-asset/ghcide#391]
I'm playing around with using VS code and ghcide, mostly because it has the progress bar which I can't work out how to show in Emacs. However, I'm finding ghcide frequently gets stuck - it'll be fine on a file and I'll be applying lots of hints, and then all of sudden the progress bar will just read something like "11/13828" and never change. 

What should I do in this case? Is there anything I can do to get insight into what ghcide is doing that might be useful for developers?

**Comment by ocharles** [comment]
Ok, I found the actual problem in this case was the code hint to `>=.` to my imports didn't surround it in parenthesis so I had a syntax error I didn't spot. But even then, resolving that has got me to 11051/13828 and that number isn't changing.

**Comment by ndmitchell** [comment]
See #379 for the patch that makes this in terms of more explicable numbers and #381 which explains why it sometimes gets stuck. I was going to investigate the latter tomorrow.

**Comment by ocharles** [comment]
Ah cool, I thought #379 had already landed (as I'm running `HEAD`), but I see that's no true. I'll keep an eye on #381, too. Thanks!
