### ISSUE TITLE
How do handlers return errors?

### ISSUE THREAD

**Issue by alanz** [digital-asset/ghcide#395]
We have

```haskell
data WithMessage = WithMessage
    {withResponse :: forall m req resp . (Show m, Show req) =>
        (ResponseMessage resp -> LSP.FromServerMessage) -> -- how to wrap a response
        (LSP.LspFuncs () -> IdeState -> req -> IO resp) -> -- actual work
        Maybe (LSP.Handler (RequestMessage m req resp))
...
    }
```
But `ResponseMessage resp` defines a response message with a `result` field of type `resp`.  A response message may not have a `result` field, but an `error` field instead. (see https://github.com/alanz/haskell-lsp/issues/191)

If the handler has an error, how is this currently handled?

Should the work part rather be

```haskell
(LSP.LspFuncs () -> IdeState -> req -> IO (Either ResponseError resp))
```
?

**Comment by cocreature** [comment]
We don’t have a nice way of handling this, there is still a TODO for this somewhere in the `daml` codebase https://github.com/digital-asset/daml/blob/a754a2aa229ae41afec045fb7722a685730150d7/compiler/damlc/daml-ide/src/DA/Daml/LanguageServer/Visualize.hs#L29. I haven’t thought too much about it but your proposal sounds sensible.

**Comment by cocreature** [comment]
We do catch exceptions and turn them into failed responses so that is something that you can use atm but it gives you very little control over the exact error that is sent back.

**Comment by alanz** [comment]
Ok, I assumed it was something like that.  But I think an explicit return is good, especially as `ResponseError` is a rich data type
