### ISSUE TITLE
Dredge up ghc-shake and use for great good

### ISSUE THREAD

**Issue by Ericson2314** [digital-asset/ghcide#399]
https://github.com/ezyang/ghc-shake shouldn't go to waste!

**Comment by cocreature** [comment]
Do you have anything specific that you’re thinking off? I’ve looked at it a while back and couldn’t really find anything that would help us.

**Comment by Ericson2314** [comment]
I didn't have anything particular in mind. I don't know much about how ghcide uses or doesn't use the GHC API, but thought I'd make an issue as I couldn't find anything.

**Comment by ndmitchell** [comment]
I don't think there's anything of use. We deliberately try and adhere to the API GHC provides, without having or relying on changes. I suspect the changes required for that branch mirror the changes we'd like, to turn it into a series of steps that are each composable and separate, but until it goes upstream, it doesn't provide much benefit :(

**Comment by Ericson2314** [comment]
Err I didn't think there was any branch of GHC involved? There was a fork of shake but I doubt that's needed.

**Comment by ndmitchell** [comment]
Hmm, it wasn't what I thought it was... It certainly could have been very helpful had we found it right at the beginning, but I suspect now the utility has gone.
