### ISSUE TITLE
Checking benchmark files

### ISSUE THREAD

**Issue by robstewart57** [digital-asset/ghcide#407]
It'd be nice to use ghcide on benchmark files.
My cabal file includes:

```
benchmark mylib-bench
  type:             exitcode-stdio-1.0
  main-is:          Benchmarks.hs
  hs-source-dirs:   bench
  build-depends:    base >= 4.7 && < 5,
                    deepseq,
                    criterion
  ghc-options: -Wall -threaded -rtsopts
  default-language: Haskell2010
```
When running `ghcide` I get:

```
ghcide bench/Benchmarks.hs
...
Step 6/6: Type checking the files
File:    
  /home/me/mylib/bench/Benchmarks.hs
Hidden:   no
Range:    5:7-5:16
Source:   not found
Severity: DsError
Message: 
  Could not load module ‘Criterion’
  It is a member of the hidden package ‘criterion-1.5.6.1’.
  You can run ‘:set -package criterion’ to expose it.
  (Note: this unloads all the modules in the current scope.)
```

How can I make `ghcide` aware of the `build-depends` libraries in the `benchmark` section of the cabal file?

**Comment by fendor** [comment]
By writing in your `hie.yaml`
```yaml
cradle:
  cabal:
    component: "bench:mylib-bench"
```

Or when using stack:
```yaml
cradle:
  stack:
    component: "mylib:bench:mylib-bench"
```

**Comment by robstewart57** [comment]
I've tried this. Now I get:

```
Step 3/6, Cradle 1/1: Loading /home/me/mylib/hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: <command line>: cannot satisfy -package mylib-0.1.0.0
    (use -v for more information)
```
However, the cabal file name is `mylib.cabal`, it is the same top level in the directory structure (i.e. in the same directory as `mylib.cabal` and this cabal file contains:

    name: mylib

**Comment by fendor** [comment]
Would you mind trying if `cabal v2-repl bench:mylib-bench`  succeeds? Also, maybe you dont depend on mylib in your benchmarks?

**Comment by robstewart57** [comment]
I was using `stack`, so:

    stack repl mylib:bench:mylib-bench

Which threw the "cannot satisfy" error above.

Turns out I had to manually `stack build` first. Now `ghcide` (and `stack repl stack repl mylib:bench:mylib-bench`) is fine:

```
Step 5/6: Initializing the IDE

Step 6/6: Type checking the files

Completed (1 file worked, 0 files failed)
```

Thanks for your guidance.

**Comment by robstewart57** [comment]
though I've now come across this issue where `ghcide` does not currently support multiple cradles: https://github.com/digital-asset/ghcide/issues/285#issuecomment-567415225

Whereby with the new `hie.yaml` in place, `ghcide` now has trouble with my library implementation files in `src/`. Presumably I'd need something like:

```
cradle:
  stack:
    - path: "./src"
      component: "mylib:lib"
    - path: "./bench"
      component: "mylib:bench:mylib-bench"
```

**Comment by fendor** [comment]
Yeah, this issue would be solved by multi-cradles, afaict. But the initial issue is solved, right? You can load the bench component and work with it?

**Comment by robstewart57** [comment]
True, you've helped me solve my initial problem thanks. I'll close this issue.
