### ISSUE TITLE
Provide prebuilt binaries

### ISSUE THREAD

**Issue by i-am-the-slime** [digital-asset/ghcide#42]
This would avoid a lot of hassle and the environment would certainly agree.

**Comment by ndmitchell** [comment]
How do you currently get your Haskell binaries? Stack? Nix? Cabal? I suspect we need different integrated installation methods for each.

**Comment by cocreature** [comment]
Building fully statically linked binaries is quite a challenge for Haskell and not one that I want to tackle at the moment. And outside of that, they cause more trouble than they help sadly. Nix avoids that issue.

There is also the problem of making sure that `ghcide` is built with the same version of GHC that you are using so we would need to provide tons of different binaries (8.6.1, 8.6.2, 8.6.3, …)

**Comment by i-am-the-slime** [comment]
Wow, thanks to you both for the incredibly quick replies. 
@ndmitchell Right now I used stack

@cocreature I actually thought providing a list of different binaries for all these ghc versions would be a plus. But I remember now that building static binaries in Haskell is difficult. I suppose there are more important issues to solve!

**Comment by ndmitchell** [comment]
Stack already has an ide subcommand that installs the Intero IDE and configures it properly for your GHC etc. It could certainly get a ghcide command that did similarly. Something for Stack to consider.

**Comment by i-am-the-slime** [comment]
Actually, I'm trying to use this again now, and I feel like this should remain open. Somehow in Purescript land it seems to be possible to provide static binaries for purescript, spago, and purty which are all Haskell projects.

**Comment by ndmitchell** [comment]
@i-am-the-slime who would this be useful for? ghcide the binary is only useful with a complete and working ghc installation. If you've got one of those, why not use it to install ghcide? I provide a static binary for HLint, so we know how to do it, I just don't see the advantage here. It's also important that the binary is compiled with exactly the same version of GHC as installed on your computer, which is hard with a single binary download.

**Comment by ndmitchell** [comment]
I think this providing prebuilt binaries would be a feature of https://github.com/haskell/ide, as per https://neilmitchell.blogspot.com/2020/01/one-haskell-ide-to-rule-them-all.html

**Comment by i-am-the-slime** [comment]
@ndmitchell Sorry, I didn't see your answer earlier. It takes  quite a while and quite a bit of energy to build this from scratch every time. Especially if you have projects on various ghc versions. That would be my main reasons. It could also be bundled with Editor plugins.

**Comment by ndmitchell** [comment]
@i-am-the-slime I think the IDE project is planning to provide pre-built binaries that integrate Ghcide with editor plugins, so I suggest raising a ticket there.
