### ISSUE TITLE
ghcide failing with linker errors due to missing symbols

### ISSUE THREAD

**Issue by merijn** [digital-asset/ghcide#425]
In my store I have both a dynamic and static version of the library for `persistent-sqlite`, the static library is missing symbols from `libc`, causing some symbols to fail to load, triggering linker failures in every module transitively depending on this. See my comments here: https://github.com/digital-asset/ghcide/issues/256#issuecomment-580672579

**Comment by fabioluz** [comment]
I'm having the same issue, caused by `persistent-template`. It happens when I add a custom newtype in the `persistLowerCase` by using persistent's quasi-quote syntax.

**Comment by merijn** [comment]
oh, lol, I forgot I already opened this issue when mpickering asked me to make one. This issue is obsoleted by the more in-depth issue https://github.com/digital-asset/ghcide/issues/550

It turns out the issue is that ghcide *must* be build dynamically, instead of the default static.

**Comment by mpickering** [comment]
@fabioluz Please either try to fix suggested by @merijn in #550 or make a new ticket.
