### ISSUE TITLE
Outline view contains too many imports

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#438]
The outline view lists every import my module makes (which are almost entirely uninteresting), followed by the functions if I scroll enough (which has lots of great information). Would be better if the imports were either collapsed by prefix (e.g. Data.* under one tree view), or probably just replaced with the word "imports", or even omitted entirely.

I'm not actually sure if it's Ghcide which is populating this or the Haskell syntax language thing. I hope @shayne-fletcher both knows and knows how to fix it :). If it is the syntax highlighting I suggest the Haskell IDE crew reach out and engage with them about it, and treat that part as part of the whole IDE ecosystem.

![image](https://user-images.githubusercontent.com/1651197/74639837-7e8e7200-5166-11ea-8d08-000659b67924.png)

**Comment by pepeiborra** [comment]
It is populated by ghcide, I implemented it. Not too happy with the end result either. Should be a relatively easy fix if anyone wants to give it a go, the only tricky bit would be reading the lsp spec for outline item types and figuring out the right way to describe the grouped imports.

**Comment by fendor** [comment]
If nobody else wants to tackle this right now, I would like to give it a try later this day. Looks like a good first issue to me.

**Comment by ndmitchell** [comment]
@pepeiborra I saw it pop up and my reaction was "what's this magic" - Ghcide keeps getting better through your efforts and others like magic. Thanks for the feature!

**Comment by ocharles** [comment]
I just want to say that it _is_ useful for me to have all the imports. If I need to jump to a specific import line I can hit `SPC s i` (search for symbol in Emacs) and then type `imp Cont Mo`, which is a fuzzy search for `import Control.Monad`. I don't use this _that_ often, but just wanted to say there is some value in what currently happens. But maybe that symbol listing is separate from the tree view you get (or also maybe it's coming from Emacs imenu, and not `ghcide`).
