### ISSUE TITLE
cannot satisfy -package-id ghc-8.6.5

### ISSUE THREAD

**Issue by gvolpe** [digital-asset/ghcide#439]
I keep on encountering this issue in different projects and I don't know how to properly solve it. This is the error I get on a folder containing two standalone Haskell files that compile in a REPL:

```
ghcide version: 0.0.6 (GHC: 8.6.5) (PATH: /nix/store/y6srcy029ah4j3d8rrdghg9b00spzhci-ghcide-0.0.6-exe-ghcide/bin/ghcide)
Ghcide setup tester in /workspace/oss/why-fp.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /workspace/oss/why-fp
Found 2 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /workspace/oss/why-fp
Cradle {cradleRootDir = "/workspace/oss/why-fp", cradleOptsProg = CradleAction: default}

Step 4/6, Cradle 1/1: Loading GHC Session
Loaded package environment from /home/gvolpe/.ghc/x86_64-linux-8.6.5/environments/default
ghcide: <command line>: cannot satisfy -package-id ghc-8.6.5
    (use -v for more information)
```

There's no `cabal` nor `stack`, just single Haskell files, but I also get the same error in bigger Haskell projects using Cabal 3.x.

## Versions

```
> ghcide --version
ghcide version: 0.0.6 (GHC: 8.6.5) (PATH: /nix/store/y6srcy029ah4j3d8rrdghg9b00spzhci-ghcide-0.0.6-exe-ghcide/bin/ghcide)

> which ghcide
/home/gvolpe/.nix-profile/bin/ghcide

> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

> which ghc
/home/gvolpe/.nix-profile/bin/ghc
```

I installed `ghcide` using Nix (https://github.com/hercules-ci/ghcide-nix).

Has anyone experienced the same issue?

**Comment by zhujinxuan** [comment]
Have you tried `NIX_GHC_LIBDIR=$(ghc --print-libdir)`?

**Comment by gvolpe** [comment]
I don't think I have tried that. Anyway, my hard drive just died so I don't have a laptop where to try this at the moment.

Feel free to close.

**Comment by jinwoo** [comment]
I also saw a similar error when I upgraded Stackage to lts-15.0 (GHC 8.8.2). But it was a non-nix environment. Just a plain stack project.

**Comment by ndmitchell** [comment]
Note that the GHC package is hidden by default, so my guess is that the hie.yaml isn't exposing it.

**Comment by jinwoo** [comment]
I think I know why this happened (at least in my case). I forgot to compile `ghcide` with GHC 8.8.2 when I created the project using Stack LTS-15.0. AFAIK both `ghcide` and the code against which it is run, must be compiled with the same version of GHC.

**Comment by gvolpe** [comment]
Thank you all for the insights! I'm closing this for now since I cannot reproduce on a fresh install.
