### ISSUE TITLE
How to debug undefined symbol: base_DataziTypeableziInternal_typeRepKind1_closure

### ISSUE THREAD

**Issue by 3noch** [digital-asset/ghcide#449]
I'm hitting this when running `ghcide` in my `nix-shell` with a small direct cradle. How can I debug what's going on?

```
Hidden:   no
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Unexpected usage error
  can't load .so/.DLL for:
  /nix/store/3ybbc3vag4mpwaqglpdac4v413na3vhl-ghc-8.6.5/lib/ghc-8.6.5/binary-0.8.6.0/libHSbinary-0.8.6.0-ghc8.6.5.so
  (/nix/store/3ybbc3vag4mpwaqglpdac4v413na3vhl-ghc-8.6.5/lib/ghc-8.6.5/binary-0.8.6.0/libHSbinary-0.8.6.0-ghc8.6.5.so:
  undefined symbol: base_DataziTypeableziInternal_typeRepKind1_closure)
```

**Comment by 3noch** [comment]
To repro:

```
git clone https://github.com/obsidiansystems/obelisk -b eac@ghcide
cd skeleton
nix-shell default.nix -A shells.ghc
ghcide
```

**Comment by mpickering** [comment]
Is this with master? Looks like an issue I recently fixed.

**Comment by 3noch** [comment]
Yes, currently on `1e68cb0e05b243ee22c7da4d864f1b4dce623b63` brought in by https://github.com/3noch/ghcide-nix/blob/7e1271f39bc7c0c120409bc88b6fe4a043cea589/nix/sources.json

**Comment by 3noch** [comment]
I thought it looked similar to your fix too and hoped upgrading to master would help but alas.

**Comment by 3noch** [comment]
This is triggered by a TH splice in `Common/Route.hs`. Hopefully I can create a minimal repro.

**Comment by 3noch** [comment]
Ok actually this is triggered by *any* TH splice that I've tried, all of which were imported from libraries provided by nix in the shell. Perhaps there's something about linking those in during TH that's no working.

I'm assuming that TH splices like `makeLense` work for other users of ghcide... Could this be at all related to the fact that my nix-shell is building Haskell libraries with standard `nixpkgs` and `ghcide-nix` builds them with `haskell.nix`?

**Comment by 3noch** [comment]
Ok I've confirmed this was due to the fact that the `ghc` used by `ghcide` was different than the one used by the packages.

**Comment by 3noch** [comment]
Perhaps this restriction could be documented better?

**Comment by mpickering** [comment]
@3noch you should probably point out that the reason you were running into issues is that you were using a patched version of GHC, so even checking the version number wouldn't have helped out.

**Comment by 3noch** [comment]
Good point. Thanks.
