### ISSUE TITLE
Add windows to azure ci

### ISSUE THREAD

**Issue by jneira** [digital-asset/ghcide#455]
* The project is not tested in ci with windows and it would catch some issues earlier
* Not sure it it had been tried and some issue made it not feasible
* The setup for haskell-ide-engine could be used as reference: https://github.com/haskell/haskell-ide-engine/blob/master/.azure/windows-stack.yml

**Comment by cocreature** [comment]
I don’t think we tried this for `ghcide` but I wouldn’t expect any issues. We do have a Windows CI for DAML (using Azure but with our own nodes).

**Comment by jneira** [comment]
I've started to add windows jobs here: https://github.com/digital-asset/ghcide/compare/master...jneira:azure-win
I am afraid that there are failing tests locally and [in the azure job](https://dev.azure.com/jneira/haskell-language-server/_build/results?buildId=671&view=logs&j=e1cdc3ba-d350-5316-ec13-eb42af08d462&t=7a50eee9-1f6e-54c4-bd87-844ba23b4a40)
