### ISSUE TITLE
Avoid parsing sources for dependencies

### ISSUE THREAD

**Issue by pepeiborra** [digital-asset/ghcide#505]
Now that ghcide is using interface files, it would be desirable if ghcide parsed only the module headers to spy out the imports and skipped the rest of the file, just like GHC does.

**Comment by pepeiborra** [comment]
I have started working on this, continuing with a previous effort at https://github.com/pepeiborra/ghcide/pull/1

**Comment by mpickering** [comment]
Does parsing the imports require an `HscEnv`? It would be good for multi-component if it didn't.

**Comment by pepeiborra** [comment]
It requires some `DynFlags`, but I think not an `HscEnv`

**Comment by pepeiborra** [comment]
Scratch that, an `HscEnv` is required to preprocess the source files before parsing the imports.

**Comment by pepeiborra** [comment]
I have a working implementation now, planning to send a PR soon. All the uses of `GetParsedModule` removed; haddocks are now embedded in `.hi` files, and ghcide doesn't even need to watch workspace files anymore.

Some early measurements suggest an important startup time improvement:

- before: 1m20s
- after: < 30s 

Memory usage does not seem to improve that much

**Comment by mpickering** [comment]
Nice one @pepeiborra If you point me to your branch I will do a review.

**Comment by pepeiborra** [comment]
Branch is https://github.com/pepeiborra/ghcide/tree/mod-summary but it's not ready for review yet. I plan to clean up and submit a PR today or tomorrow
