### ISSUE TITLE
Cannot find module X from test suite

### ISSUE THREAD

**Issue by emlautarom1** [digital-asset/ghcide#514]
Setup:
- **GHC**: 8.8.3
- **ghcide**: 0.1.0
- **Editor**: VSCode 1.43.2
- **Editor Extension**: ghcide 0.0.2
- **OS**: Windows 10 v1909

I'm trying out the tool and I find that there are some imports that `ghcide` cannot resolve, but `GHCi ` through `cabal` can. 

My project structure is something like the following:

```
- src
   - ModuleA.hs
- test
  - ModuleATest.hs
- myproject.cabal
- ...
```

In `ModuleATest` I'm importing `ModuleA` for testing but `ghcide` reports `Could not find module 'ModuleA'`. On the other hand, `GHCi` (through `cabal repl MyProject-test`) can find the module and run the test suite with no problems.

The exact error I get is:
```
Could not find module `ModuleA'
It is not a module in the current program, or in any known package
```

Also, warnings like `-Wunused-imports` are not being picked up, but that's not the main issue here.

This is a part of my `MyProject.cabal` file

```cabal
name:                MyProject
...
library
  exposed-modules:
    ModuleA
  build-depends:     base >= 4.12.0.0
  hs-source-dirs:    src
  default-language:  Haskell2010
  ghc-options:
    -Wall
    -Wincomplete-record-updates

test-suite MyProject-test
  type:             exitcode-stdio-1.0
  main-is:          ModuleATest.hs
  hs-source-dirs:   test
  default-language: Haskell2010
  build-depends:       
      MyProject
    , base >= 4.12.0.0
```

I think this might be a duplicate of #470, but in this case, I'm not using any third-party libraries and I'm not getting a "hidden package error" but a "could not find module".

**Comment by fendor** [comment]
Your `myproject.cabal` files looks wrong, to be specific, your `test-suite`. In your `build-depends`, you specify `ModuleA` which looks like it is the module from your library. This is invalid, the build-depends section is *only* for package dependencies, e.g. you could have written:
```cabal
test-suite myproject-test
  type:             exitcode-stdio-1.0
  main-is:          ModuleATest.hs
  hs-source-dirs:   test
  default-language: Haskell2010
  build-depends:       
      myproject
    , base >= 4.12.0.0
```
which signals cabal that your test-suite depends on the library of your project, assuming your package is named `myproject`.

I would have expected that `cabal test` and `cabal repl test:myporject-test` show some warnings, but maybe not.

**Comment by emlautarom1** [comment]
Indeed, this is wrong. I changed some module names since this is a personal project but it seems like a made a mistake. I'll correct it.

The issue stands. Please, check the updated issue description

**Comment by fendor** [comment]
You should provide the debug output, e.g. from `ghcide test/ModuleATest.hs` or share your exact project if it is on github. 
Alternatively, you could check if adding a `hie.yaml` such as 
```yaml
cradle:
  cabal:
    component: "test:myproject-test"
```
to the root of your project solves the problem. If yes, this is likely a mistake in the automatic project detection.

**Comment by emlautarom1** [comment]
The provided solution works flawlessly. Adding a `hie.yaml` file like that to the root of the project allows `ghcide` to correctly check the import.

Should I report the bug to another repo as well, or this is strictly a `ghcide` bug?

**Comment by fendor** [comment]
I think this is expected behaviour of [hie-bios](https://github.com/mpickering/hie-bios/) which also has more documentation for the `hie.yaml` specification. Note though, that ghcide does not support multi-cradles yet, see #361.

**Comment by emlautarom1** [comment]
Closing since this issue is related to [hie-bios](https://github.com/mpickering/hie-bios/) and not `ghcide`.
