### ISSUE TITLE
Quasiquoter suggestions/quick-fixes

### ISSUE THREAD

**Issue by runeksvendsen** [digital-asset/ghcide#526]
I don't know much about the internals of `ghcide` (or GHC), so please bear with me, but I'd like to discuss the idea of having `ghcide` offer e.g. suggestions and quick-fixes for quasi-quoters, by having quasi-quoters output errors of a particular format.

Some things I would like feedback on:

1. Is this desirable?
    1. I'd argue yes, as it would be a simple way for e.g. [SQL quasiquoters](http://hackage.haskell.org/package/postgresql-simple-0.6.1/docs/Database-PostgreSQL-Simple-SqlQQ.html) to add suggestions and quick-fixes
2. Is it doable?
3. What would be a sensible error format for the quasiquoter, which `ghcide` needs to parse?
    1. Off the top of my head, I'm thinking it would be most practical if this format were both human-readable and easily parseable (i.e. no JSON/XML/YAML) so that we don't restrict quasiquoters to be only readable by humans or usable by `ghcide`

**Comment by mpickering** [comment]
You can use `qReport` or `qError` to report errors in quasiquoters which will display in ghcide.

**Comment by runeksvendsen** [comment]
Thanks!

When I use `qReport True (Text.Megaparsec.Error.errorBundlePretty e)` to indicate an error it works, but the entire quotation is underlined with a red squiggly line.

Is there a way to pass some form of `Language.Haskell.TH.Loc` to `ghcide` so that only the offending source span is underlined?

**Comment by mpickering** [comment]
I don't think so. How would you get the right `Loc` to report?

**Comment by runeksvendsen** [comment]
I haven't had the time to play with quasi-quoters until yesterday, but before that I assumed that the quasi-quotation mechanism allowed the parser to throw an error containing an offset in the raw quasi-quoted string (i.e. what's between `[|<quoter>` and `|]`), which GHC would translate into the correct line/column in the source file. 

This doesn't seem to be the case unfortunately. However, the parser can output the correct Haskell source span by taking as input the output of `Language.Haskell.TH.Syntax.location` (which provides the source span for the quoted string in the Haskell source file), and using this to translate its internal offset (in the string that follows `[|<quoter>` and precedes the ending `|]`) into a Haskell source file offset.

After this, the task concerns serializing this information in some way into an error message so that `ghcide` can grab it, parse it into a `Loc` span, and display an error/warning at the given line (see point 3 above).

**Comment by mpickering** [comment]
The right way to fix this is to modify GHC so that `qReport` can also take a source span to report at or your idea of providing an interface which takes an offset is a good one as well.

**Comment by runeksvendsen** [comment]
I completely agree that modifying GHC, and adding e.g. `qReportLoc :: Quasi m => Bool -> String -> Loc -> m ()`, would be the right fix for this. However, this would not enable the feature for GHC versions less than 8.12 (or whenever it might be merged).

So I think it's still worthwhile to consider the option of having ghcide do the translation from quasi-quote-string Loc to Haskell source file Loc.

Also, as far as I can see, if we want to enable quasi-quoters to display suggestions via ghcide (auto-completely functionality), then ghcide would need to parse the contents of a quasi-quoter error message anyway. Thus, the concept of ghcide parsing error messages would be a requirement, and parsing LOCs would just be a special case of this.

**Comment by runeksvendsen** [comment]
Actually, thinking some more about it, suggestions ought to use the same mechanism that GHC uses for holes. I see that ghcide can provide suggestions by looking at GHC hole fits, this seems to be the right place to allow suggestions via quasi-quoters.

Generally speaking, I see the point of having as little code in ghcide as possible, and adding to features to GHC instead.

**Comment by runeksvendsen** [comment]
I’m closing this, as I agree that the right place for this code is inside GHC.
