### ISSUE TITLE
Doesn't respect preprocessors defined by bios cradle

### ISSUE THREAD

**Issue by 3noch** [digital-asset/ghcide#531]
I have a `hie.yaml` that uses a command-line tool to generate the `ghci` configuration. Several of the options are configuring a preprocessor. However, `ghcide` seems to process my files without any regard to this preprocessor. It seems `ghcide` would support the preprocessor if it's configuration were defined in the source file directly, but in my case I'm adding the preprocessor via `ghci`.

**Comment by 3noch** [comment]
cc @mpickering Perhaps this has more to do with hie-bios than ghcide, but I can't tell.

**Comment by fendor** [comment]
Please share you `hie.yaml`

**Comment by mpickering** [comment]
I have used ghcide with a preprocessor (lhs2tex) and it works. More info needed.

**Comment by 3noch** [comment]
@mpickering I've updated the title. I wasn't nearly clear enough. My `hie.yaml` looks like:

```yaml
crandel: { bios: { program: hie-bios.sh } }
```

`hie-bios.sh` simply prints out flags one per line. However, it does include `-F -pgmF ... -optF ...` flags and these are what seem to be ignored.

**Comment by 3noch** [comment]
I would expect preprocessors defined in a `cabal` file's `ghc-options` to have the same amount of support that this does.

**Comment by mpickering** [comment]
Again, needs more information and minimal reproduction. I have used a preprocess specifying `-pgmL` options so perhaps `-pgmF` is not implemented correctly/at-all in ghcide.

**Comment by ndmitchell** [comment]
Pre-processors have definitely been implemented on an ad-hoc basis, so I'd be shocked if they were all supported (it's the cost of not using downsweep).

**Comment by 3noch** [comment]
:thinking: So far my minimal repro actually works fine with `ghcide`. This may be a subtlety on my end. https://gist.github.com/3noch/80d79c8ddbc7049ae8b0e737c92f841f

**Comment by 3noch** [comment]
Yep. It was a bug on my end! So sorry for the noise. On the bright side, we all now know that `ghcide` does in fact work with this! :blush:
