### ISSUE TITLE
GHC check broken when using haskell.nix

### ISSUE THREAD

**Issue by mpickering** [digital-asset/ghcide#534]
With ghcide + haskell.nix + ghc 8.8, I'm getting

>   ghcide compiled against GHC 8.8.3 but currently using an unknown version of GHC . This is
>   unsupported, ghcide must be compiled with the same GHC version as the project.

... because ghc is broken in the package database. With `reinstallableLibGhc`, ghc just isn't in the package database. Either scenario breaks the compatibility check.

I guess in the long term, hopefully the package database stuff can be fixed, but we probably also need an opt-out flag from this check (or that it turns no ghc version information into a warning).

_Originally posted by @fiadliel in https://github.com/digital-asset/ghcide/issues/532#issuecomment-618276756_

**Comment by mpickering** [comment]
@fiadliel To clarify the issue is that the `ghc` package is NOT in the package database? It is an important assumption for the check that it is, so if this is sometimes violated then we will have to rethink how the check is performed. Perhaps checking for the `base` version  would work instead.

**Comment by fiadliel** [comment]
Okay, to demonstrate what is present in each environment, here's the situation with ghc 8.8.3, and the haskell.nix flag `reinstallableLibGhc = true`:

```

$ ghc-pkg list
/nix/store/yj3wcs26l1bc3sbfn18bmy18ljskl4gi-ghc-shell-for-packages-ghc-8.8.3-env/lib/ghc-8.8.3/package.conf.d
...
    base-4.13.0.0
...
    free-5.1.3
    ghc-boot-th-8.8.3
    ghc-heap-8.8.3
    ghc-prim-0.5.3
    hashable-1.3.0.0
...
```
(no ghc)

And then with `reinstallableLibGhc = false`:

```
$ ghc-pkg list
WARNING: there are broken packages.  Run 'ghc-pkg check' for more details.
/nix/store/31k03nmk01zmlhzv9f3jmaw0hkdzm06r-ghc-shell-for-packages-ghc-8.8.3-env/lib/ghc-8.8.3/package.conf.d
...
    base-4.13.0.0
...
    free-5.1.3
    ghc-8.8.3
    ghc-boot-8.8.3
    ghc-boot-th-8.8.3
    ghc-compact-0.1.0.0
    ghc-heap-8.8.3
    ghc-prim-0.5.3
    ghci-8.8.3
    hashable-1.3.0.0
...
```
```
$ ghc-pkg check
There are problems in package ghc-8.8.3:
  dependency "terminfo-0.4.1.4" doesn't exist

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.
ghc-8.8.3
```

In both cases, the ghcide version check fails (with no runtime version detected).

`base` does seem more reliable as a detection measure.

**Comment by mpickering** [comment]
Why does your package database have `ghc-boot-th-8.8.3` and `ghc-heap-8.8.3` in it still?

**Comment by fiadliel** [comment]
It seems to still be an area of flux for the haskell.nix developers, I would bet on it changing in future. As for why, there are issues like https://github.com/input-output-hk/haskell.nix/issues/524 around whether base ghc packages are also available in hackage.
(which leads to https://github.com/input-output-hk/haskell.nix/blob/f5b150c98a7d7ae8e414652ba20f3ccc98414f36/modules/component-driver.nix#L76 )

Oh, and I guess base wouldn't help with detecting minor version mismatches.

**Comment by fiadliel** [comment]
Or maybe it's just that dependency diagram above (that `ghc-heap` and `ghc-boot-th` are dependencies of `rts`, so can't be reinstalled.

**Comment by pepeiborra** [comment]
I agree that this is an unreasonable assumption in ghc-check. I don't know if checking the version of base is a good approximation though, does that move with every ghc minor version?
