### ISSUE TITLE
CradleError: cabal: Unrecognised target syntax for '' with `cabal.project`.

### ISSUE THREAD

**Issue by nomeata** [digital-asset/ghcide#548]
Trying to see if `ghcide` works on one of my project, but I did not get far:
```
$ ghcide
ghcide version: 0.1.0 (GHC: 8.6.5) (PATH: /nix/store/m73bb8apfwyr79759qll17w4qwq582ry-ghcide-0.1.0/bin/ghcide)
Ghcide setup tester in /home/jojo/project/impl.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /home/jojo/project/impl
Found 34 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /home/jojo/project/impl
Cradle {cradleRootDir = "/home/jojo/project/impl", cradleOptsProg = CradleAction: Cabal}

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling cabal","","cabal: Unrecognised target syntax for ''.\n\n",""]
```

Interestingly it works if I remove the following file
```
$ cat cabal.project 
packages: .
```
The `cabal.project` file used to be more interesting than this, but if I read https://www.haskell.org/cabal/users-guide/nix-local-build.html#cfg-field-packages correctly then this is pretty much equivalent to the default… 🤷

It also fails with
```
packages: ./*.cabal
```

Maybe a `cabal` bug? This is
```
$ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
```

**Comment by mpickering** [comment]
Does `cabal v2-repl` work without a target? Otherwise you will have to specify a `hie.yaml` to pick a specific target with the current master branch.

**Comment by nomeata** [comment]
After removing the `cabal.project`, running `ghcide` seems works fine if I have a `.ghc.environment.x86_64-linux-8.6.5` laying around, but if not I get erros like
```
Step 4/6, Cradle 1/1: Loading GHC Session

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files
File:     /home/jojo/project/impl/src/IC/Wasm/Winter/Persist.hs
Hidden:   no
Range:    76:26-76:40
Source:   typecheck
Severity: DsError
Message: 
  /home/jojo/project/src/IC/Wasm/Winter/Persist.hs:76:27: error:
  • Couldn't match expected type ‘MutVar
  (Control.Monad.Primitive.PrimState (ST s)) W.Value’
  with actual type ‘primitive-0.6.4.0:Data.Primitive.MutVar.MutVar
  (primitive-0.6.4.0:Control.Monad.Primitive.PrimState (ST s))
  W.Value’
  NB: ‘primitive-0.6.4.0:Data.Primitive.MutVar.MutVar’
  is defined in ‘Data.Primitive.MutVar’
  in package ‘primitive-0.6.4.0’
  ‘MutVar’
  is defined in ‘Data.Primitive.MutVar’
  in package ‘primitive-0.7.0.0’
  • In the first argument of ‘readMutVar’, namely ‘(W._giContent m)’
  In the expression: readMutVar (W._giContent m)
  In an equation for ‘persist’:
  persist m = readMutVar (W._giContent m)
  • Relevant bindings include
  m :: W.GlobalInst (ST s)
  (bound at /home/jojo/project/impl/src/IC/Wasm/Winter/Persist.hs:76:11)
  persist :: W.GlobalInst (ST s)
  -> M (W.GlobalInst (ST s)) (Persisted (W.GlobalInst (ST s)))
  (bound at /home/jojo/project/impl/src/IC/Wasm/Winter/Persist.hs:76:3)
```
so it seems it’s resolving different dependencies?

With the environment file around (e.g. after `cabal build`), running `ghcide` goes through. 

Indeed `cabal v2-repl` complains about needing a target. Hmm, too bad.

**Comment by nomeata** [comment]
Maybe some of these issues are `nix` related… this is probably not an helpful actionalbe focused issue; I’ll close it to reduce the noise on the issue tracker.

**Comment by mpickering** [comment]
I described how to fix the problem in the first comment! Just add a hie.yaml file which specifies the right component and it will work.

**Comment by nomeata** [comment]
Yes, thanks, I’ll look into that (still searching for the documentation of hie.yaml, though :-) 

Ah, there is a link from https://github.com/digital-asset/ghcide to https://github.com/mpickering/hie-bios#readme. All good!
