### ISSUE TITLE
hie-bios program called without file path

### ISSUE THREAD

**Issue by hyperfekt** [digital-asset/ghcide#551]
I implemented a program to provide flags to hie-bios and was dismayed to find that ghcide calls it with an empty file path. This clearly violates the hie-bios API, and the resulting requirement that bios programs provide flags without any path given, counter to the documentation of hie-bios, is not documented.

**Comment by mpickering** [comment]
This is fixed in #522 and on my fork (https://github.com/mpickering/ghcide)

**Comment by fendor** [comment]
This can be closed now
