### ISSUE TITLE
librt.so: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by tchoutri** [digital-asset/ghcide#560]
Hi, I am trying to compiler master (c7c3982, actually) with the following command:

`stack install --stack-yaml=stack810.yaml --ghc-options=-O2`

And I get the following error:

```
shake > <command line>: /nix/store/dp9nhj3ng2hw3cfn0x0w867z0d3kp0i7-glibc-2.30/lib/librt.so: 
undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
```

I do use Stack's nix integration with the following packages `[glpk, pcre, zlib]`.
Do I need to add something else?

**Comment by mpickering** [comment]
How are you compiling master? That error makes it look like you have glibc mismatch somewhere.

**Comment by tchoutri** [comment]
@mpickering I ran a `stack clean --full` beforehand and ran the command I described above.

**Comment by tchoutri** [comment]
@mpickering I managed to have a workaround (thanks to @immae) with `LD_PRELOAD=/lib64/librt.so`. Closing this issue.
