### ISSUE TITLE
Fails when a file uses the PackageImports extension

### ISSUE THREAD

**Issue by ilyakooo0** [digital-asset/ghcide#569]
I am fairly certain that the following error is related to the use of the PackageImports extension in the currently open file.

```
ghcide: very bad
CallStack (from HasCallStack):
  error, called at src/Development/IDE/Import/FindImports.hs:78:23 in ghcide-0.1.0-B7KZ16czJifIz5r3YZOrKr:Development.IDE.Import.FindImports
```

**Comment by mpickering** [comment]
You appear to be using my branch, so please open an issue on my fork rather than here.

**Comment by ilyakooo0** [comment]
That is true.
Will reopen on your branch then.

**Comment by seagreen** [comment]
I believe this can be closed.
