### ISSUE TITLE
GHCIDE fails in quasi-quote expressions (cannot find symbols)

### ISSUE THREAD

**Issue by fabioluz** [digital-asset/ghcide#581]
Hi, I have an issue very similar to #550 and #425. I didn't understand the proposed solutions for them.

I'm using the library `persistent-template` and GHCIDE fails in recognizing a quasi-quote expression, showing the following error message:

```
Program error: 
ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  RideziSharedziTypes_Email_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
```

In #550, it says that adding `add executable-dynamic: True` to the cabal.project fixed the issue. I don't have a cabal.project, I'm using `stack`. I have a `package.yaml` and `project.cabal`. I tried adding `add executable-dynamic: True` project.cabal but it made no difference.

I also tried adding `-dynamic` to the `ghc-options` in `package.yaml`. After that the error message changed to:

```
Cannot load -dynamic objects when GHC is built the normal way
  To fix this, either:
    (1) Use -fexternal-interpreter, or
    (2) Build the program twice: once the normal way, and then
        with -dynamic using -osuf to set a different object file suffix.
```

In #425, it says: `It turns out the issue is that ghcide must be build dynamically, instead of the default static.`

How do I do that? I installed GHCIDE with Nix, following the instructions in the repository. Should I download the source code, change something and build it manually in this case?

Thanks in advance.

**Comment by mpickering** [comment]
I think this is fixed if you build from master. Try that?

**Comment by fabioluz** [comment]
Ok. I can do that but I need some guidance.

I just cloned from master, I see the project uses `nightly-2019-09-16` which is `ghc-8.6.5`. My project uses `ghc-8.8.3`. What do I have to change to build ghcide in the same ghc version my project uses? Can I just change ghcide `stack.yaml` to the same resolver I'm using?

**Comment by cocreature** [comment]
> Can I just change ghcide `stack.yaml` to the same resolver I'm using?

Yes, that should work.

**Comment by fabioluz** [comment]
`stack install` always throws an error. I tried changing the resolver to `lts-15.12` as well as using the `stack88.yaml` file. I get this error:

```
shake               > Registering library for shake-0.18.5..
                     
--  While building package ghc-check-0.3.0.1 using:
      /home/superfabio/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.0.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

Sometimes the errors happens with another package.  Any ideas of what it could be?

**Comment by fabioluz** [comment]
The problem was that I didn't have `ghc` as stand-alone installation, so running `apt-get install ghc ghc-prof ghc-doc` solved that.

After installing `ghcide` from master, the issue was gone, so it was indeed fixed 👍 

Thank you!
