### ISSUE TITLE
Register FileExistsVar global unconditionally

### ISSUE THREAD

**Issue by pepeiborra** [digital-asset/ghcide#599]
This is to avoid confusing error messages with buggy clients that:

1. do not advertise support for WatchedFiles, and
2. send unrequested WatchedFiles notifications.

This has been reported originally in https://github.com/haskell/haskell-language-server/issues/143

**Comment by ndmitchell** [comment]
I'm going to spin a patch for this, if you don't have it already in hand?

**Comment by pepeiborra** [comment]
Please do
