### ISSUE TITLE
Module saving unloads module with LanguageClient-neovim

### ISSUE THREAD

**Issue by tomsmeding** [digital-asset/ghcide#618]
I'm afraid this is an issue with the combination of LanguageClient-neovim and ghcide, and I'm not sure which is to blame. The reproduction below does not result in any errors when using VSCode as far as I can determine.

Reproduction:
1. Make an empty directory, and put [the files from this Gist](https://gist.github.com/tomsmeding/e3a315a0c58f296cb92f6a85b49faa7e) in that directory.
2. Ensure that you have a `neovim` installation with LanguageClient-neovim set to use `ghcide --lsp` for `haskell` files. If I need to be more precise about this step, please let me know.
3. Open `Main.hs` and `Submod.hs` using `nvim`. No errors should be displayed at this point (as indeed there are none).
4. Add an `x` in the `42` literal in `Submod.hs`; do not yet save the file. This produces a diagnostic that the variable `x2` is not defined, as expected.
5. Remove the `x` from the `42` literal. All diagnostics disappear again, as expected.
6. Save the file `Submod.hs`. **Now a diagnostic is emitted in `Main.hs` stating that the module `Submod` cannot be found.**

This last diagnostic is why I am writing this issue. As far as I know, the only workaround is to stop the language server (`:LanguageClientStop`), remove `ghcide`'s cache (`rm -rf ~/.cache/ghcide`), and start the server again (`:LanguageClientStart`).

I can do more debugging if you wish, but I'm not sure where to look, as I'm not familiar with the LSP (and thus cannot see at a glance if there's anything wrong with the messages being exchanged).

Also, if this is really an issue with LanguageClient-neovim, please let me know.

**Comment by tomsmeding** [comment]
Further note: adding a `hie.yaml` with the following contents does not help:

```
cradle:
  cabal:
    - path: "."
      component: "test:exe:test"
```

Though if you want to try this, make sure that LanguageClient-neovim detects the project root correctly. Due to a bug, you may need to place an (e.g. empty) `stack.yaml` file in the current directory. This is just for "project root" detection, nothing else.

**Comment by tomsmeding** [comment]
This is an issue in LanguageClient-neovim; it incorrectly handles file watch registrations. In the reproduction project in the gist above, `ghcide` puts a file watch on `Submod.hs`. When a file is saved in vim and `backupcopy` is not set to `yes` (and indeed, by default, it is set to `auto`), a copy is written and then renamed over the original. LanguageClient-neovim's `notify` crate detects this as a delete event and subsequently loses the file in its watcher. `ghcide` receives a message that the file has been deleted, and thus issues the error in `Main.hs`.

I will open an issue on LanguageClient-neovim about this.

**Comment by ndmitchell** [comment]
Thanks for tracking it down @tomsmeding !
