### ISSUE TITLE
Turn on some warnings 

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#62]
By default GHC enables some warnings, but not very many. How about enabling -Wunused-binds -Wunused-imports as those are super useful in an IDE for rapid refactoring.

If people agree, we can set these before calling the cradle initialise so people can still turn them off explicitly if they want.

**Comment by cocreature** [comment]
I don’t think this is a good idea. IMHO IDEs should never deviate from CLI compilers wtr to warnings and error messages.

**Comment by jacg** [comment]
Curious, I'm not aware of having done anything to enable these warnings, and here is what happens on my machine:

`cat DefaultWarnings.hs`:

    module DefaultWarnings () where
    
    import Data.Map
    
    foo = 1 where
      bar = 4

`ghcide DefaultWarnings.hs`:

    Starting ghcide (GHC v8.6)
    /home/jacek/src/ghcide
    [1/6] Finding hie-bios cradle
    Cradle {cradleRootDir = "/home/jacek/src/ghcide", cradleOptsProg = CradleAction: direct}
    
    [2/6] Converting Cradle to GHC session
    res
      (ExitSuccess,"",["-Wunused-binds","-Wunused-imports","-Worphans","-Wunused-matches","-Wincomplete-patterns","-XBangPatterns","-XDeriveGeneric","-XGeneralizedNewtypeDeriving","-XOverloadedStrings","-XDeriveFunctor","-XLambdaCase","-XNamedFieldPuns","-XRecordWildCards","-XScopedTypeVariables","-XStandaloneDeriving","-XTupleSections","-XTypeApplications","-XViewPatterns","-package=ghc","-ignore-package=ghc-lib-parser","-ignore-package=ghc-lib","-DGHC_STABLE","-isrc","-iexe","-itest/cabal","-itest/src","-itest/exe"],"")
    ["-Wunused-binds","-Wunused-imports","-Worphans","-Wunused-matches","-Wincomplete-patterns","-XBangPatterns","-XDeriveGeneric","-XGeneralizedNewtypeDeriving","-XOverloadedStrings","-XDeriveFunctor","-XLambdaCase","-XNamedFieldPuns","-XRecordWildCards","-XScopedTypeVariables","-XStandaloneDeriving","-XTupleSections","-XTypeApplications","-XViewPatterns","-package=ghc","-ignore-package=ghc-lib-parser","-ignore-package=ghc-lib","-DGHC_STABLE","-isrc","-iexe","-itest/cabal","-itest/src","-itest/exe"]27
    ([],0)Loaded package environment from /home/jacek/src/ghcide/.ghc.environment.x86_64-linux-8.6.4
    [3/6] Initialising IDE session
    
    [4/6] Finding interesting files
    Found 1 files
    
    [5/6] Setting interesting files
    [DEBUG] Set files of interest to: [NormalizedFilePath "DefaultWarnings.hs"]
    [DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
    
    [6/6] Loading interesting files
    [DEBUG] Finishing shakeRun (took 0.00s, exception: thread killed)
    [DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
    File:     DefaultWarnings.hs
    Range:    3:4-3:19
    Source:   typecheck
    Severity: DsWarning
    Message: 
      DefaultWarnings.hs:3:5: warning:
      The import of ‘Data.Map’ is redundant
      except perhaps to import instances from ‘Data.Map’
      To import instances alone, use: import Data.Map()
    File:     DefaultWarnings.hs
    Range:    5:4-5:7
    Source:   typecheck
    Severity: DsWarning
    Message:  DefaultWarnings.hs:5:5: warning: Defined but not used: ‘foo’
    File:     DefaultWarnings.hs
    Range:    6:6-6:9
    Source:   typecheck
    Severity: DsWarning
    Message:  DefaultWarnings.hs:6:7: warning: Defined but not used: ‘bar’
    [DEBUG] Finishing shakeRun (took 0.05s, completed)
    Files that worked: 1
    Files that failed: 0
    Done
    
So, here at least, they appear to be on by default.

FWIW, I tend to agree with @ndmitchell, I really find these warnings useful and am glad that they are on without me having to work to achieve it. Though I do sympathize @cocreature's point about discrepancies between IDE and compiler behaviour.

**Comment by ndmitchell** [comment]
You are using a direct cradle which explicitly turns on the warnings listed at https://github.com/digital-asset/ghcide/blob/master/hie.yaml#L4-L8.

**Comment by jacg** [comment]
@ndmitchell Yes, that's it.

**Comment by jacg** [comment]
And if I compile ghcide with stack, ghcide fails on most files with this cradle. If I modify the cradle to look like this:

````
cradle:
    stack:
````
ghcide works again, but the warnings are turned off, so I turn the cradle into

````
cradle:
    stack:
        arguments:
            - -Wunused-binds
            - -Wunused-imports
````
but the warning don't appear.

How should these warnings be turned on when compiling with stack?

**Comment by ndmitchell** [comment]
I raised https://github.com/mpickering/hie-bios/issues/44 to add `arguments`, since that's a `hie-bios` feature.

**Comment by cocreature** [comment]
At the moment, just modifying your cabal file (done in #75 for ghcide itself) is the only option. As I mentioned before, I’m not in favor of IDEs and CLI compilers deviating here so even if `hie-bios` adds this feature, I think this is a better way of tackling this.

**Comment by ndmitchell** [comment]
FWIW I disagree on the approach. I use Cabal for distribution, but ghci for development and testing, so I always put warnings in a .ghci file but not in a .cabal file. In my view Cabal is too slow for development.

However, once hie-bios gets the feature, it can be used freely by people with ghcide, without ghcide itself taking a position on where the flags should go.

**Comment by mpickering** [comment]
Currently I am in agreement with @cocreature here that the IDE and CLI should agree with each other. 

However, seeing as cabal doesn't support defining `repl-options` in a cabal.project file then perhaps the best course of action is allow users to specify it in the hie.yaml file.

Looking over some of the cabal issues, the repl component has been really poorly supported over the years.

**Comment by jacg** [comment]
How about endowing the IDE with a switch for flipping between two states:

1. matching the CLI exactly
2. being helpful for development

There are all sorts of things that I want to see in my editor as I'm developing, which I absolutely don't want polluting the output of my compiler runs. I can imagine the use of a CLI compatibility mode in the IDE on occasion, but most of the time I want the IDE to be much more talkative.

**Comment by cocreature** [comment]
Having thought about this for a while, I don’t want to take a stance on default flags in `ghcide` so I’m closing this issue. If `hie-bios` adds a way to specify additional flags, I’d be happy to integrate that (assuming it doesn’t work without changes).
