### ISSUE TITLE
Cannot find interface-file declaration when using Plugin

### ISSUE THREAD

**Issue by Tritlo** [digital-asset/ghcide#632]
I'm workin on a type checker plugin, and I have the following code:

```haskell
getPluginTyCons :: TcPluginM PluginTyCons
getPluginTyCons =
   do fpmRes <- findImportedModule (mkModuleName "Kind.Default") Nothing
      case fpmRes of
         Found _ mod  ->
             do ptc_default <- getTyCon mod "Default"
                ptc_relate  <- getTyCon mod "Relate"
                ptc_promote <- getTyCon mod "Promote"
                ptc_ignore  <- getTyCon mod "Ignore"
                ptc_report  <- getTyCon mod "Report"
                return $ PTC { ptc_default = ptc_default
                             , ptc_promote = ptc_promote
                             , ptc_ignore  = ptc_ignore
                             , ptc_relate  = ptc_relate
                             , ptc_report = ptc_report }
        _ -> pprPanic "Module not found!" (ppr mod)
  where getTyCon mod name = lookupOrig mod (mkTcOcc name) >>= tcLookupTyCon
```
Here, `Kind.Default` is a module that is imported by the file in question and a member of exposed-modules in the cabal file. When I compile this with `cabal build`, it works great. But when I compile it with ghcide, I get the following:

```
  • Can't find interface-file declaration for type constructor or class Default
  Probable cause: bug in .hi-boot file, or inconsistent .hi file
  Use -ddump-if-trace to get an idea of which file caused the error
```

I've tried doing various combinations of `initIfaceTcRn` and `loadPluginInterface`, and it still works in Cabal (both run and repl), but keeps failing when I run ghcide.

I suspect this may be related to #614, since the this is also a case of a `tcLookup` from external code (here a plugin, there in template haskell) during compilation.

I'm running `ghcide version: 0.2.0 (GHC: 8.10.1)` with no cradle. This happens both on the command line and in the editor, I'm running on Ubuntu 20.04, with GHC 8.10.1 from Nix and ghcide installed by running `cabal install` after pulling the library from github.

**Comment by pepeiborra** [comment]
Thanks for the bug report. 
Are you able to provide a minimal reproduction that we can use to investigate? Does the same work in ghci?

**Comment by Tritlo** [comment]
Sure! It works just fine with `cabal repl test`. Here's a repository which reproduces the error:

https://github.com/Tritlo/minimal-ghcide-bug

**Comment by pepeiborra** [comment]
ghcide on GHC 8.10.1 has issues with plugins, see https://github.com/digital-asset/ghcide/issues/556. That ticket links to a GHC issue, there might be more information there. 

Can you check if the issues go away with GHC 8.8.3?

**Comment by Tritlo** [comment]
It does!

**Comment by Tritlo** [comment]
The weird thing is that it works with `cabal run` and `cabal repl`, which I'd not expect if it was purely a GHC issue. Is there any way to make `ghcide` load it's interfaces in the same way cabal does?

**Comment by pepeiborra** [comment]
Cabal does not load any interface files, as far as I'm aware.

**Comment by Tritlo** [comment]
Ah, I meant "can we make `ghcide` load its interfaces the same way `cabal repl` loads the interfaces for `ghci`?

**Comment by ndmitchell** [comment]
@Tritlo `cabal repl` just calls `ghci`, to a first approximation. We do a much more nuanced loading files, and using the interfaces in different ways. If someone could track down exactly the cause of the bug, we might then be able to figure out exactly what `ghci` does differently, but there's no way to follow what `ghci` does all that closely. I think the effort needs to go into GHC here, sadly.

**Comment by Tritlo** [comment]
Yeah, that makes sense. I guess I was hoping there was some config I could generate to circumvent this while waiting for GHC to catch up. Thank you for your time!
