### ISSUE TITLE
Completions should not depend on Typecheck

### ISSUE THREAD

**Issue by pepeiborra** [digital-asset/ghcide#655]
The `ProduceCompletions` rule depends on `TypeCheck`, which means it cannot be computed until typechecking is done.

While this can be addressed by using stale data, I think it would be more elegant to improve the implementation so that it only needs the parsed module + the `ModIface` of (the transitive closure of) imports and the package database. 

Additionally, we could break down `ProduceCompletions` in two parts:

1. `ProduceCompletionsFromImports`
2. `ProduceCompletionsFromLocalModule`

The first one would have no dependency on the `ParsedModule` but only on the `ModSummary`, which is already smart enough to survive across edits that do not alter the module import list, and therefore only `ProduceCompletionsFromLocalModule` would need to be recomputed across edits.

**Comment by ndmitchell** [comment]
One day Haskell will have [working records](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0282-record-dot-syntax.rst), and on that day, completions will require the type checked module. Your plan doesn't seem unreasonable for now.

**Comment by pepeiborra** [comment]
Currently completions are not type-directed at all, which is why I think depending on typechecking is unnecessary. When record-dot-syntax lands the completion engine will need to be enhanced to support it, and we can make it depend on typechecking info when a record field is being completed, and only then.
