### ISSUE TITLE
Feature List in README

### ISSUE THREAD

**Issue by maralorn** [digital-asset/ghcide#66]
I know ghcide is quite fast moving at the moment. But while setting up my vim I was wondering if now I have everything working, which could work at the moment.

So I‘d appreciate a short list of language server functionality which is working in ghcide in the README.md. That would be very helpful!

Otherwise: Keep up the good work!

**Comment by cocreature** [comment]
Sounds like a good idea! Feel free to open a PR with a first version of this list and we can then expand it.

**Comment by maralorn** [comment]
I have really no clue, but I will give it a shot.

**Comment by cocreature** [comment]
Closing since we have an initial feature list now, thanks a lot @maralorn! We can and should gradually expand it but I don’t think keeping the issue open is useful for that.
