### ISSUE TITLE
Tests use wrong ghcide executable

### ISSUE THREAD

**Issue by jacg** [digital-asset/ghcide#74]
This is the current implementation of `ghcide` executable discovery, which is being used to start the LSP server which responds to queries sent by the test suite:

    locateGhcideExecutable :: IO FilePath
    locateGhcideExecutable = pure "ghcide"

Consequently, the tests end up talking to a server which happens to be on `$PATH`, rather than the one which is relevant to the configuration currently being tested.

**Comment by cocreature** [comment]
Afaik, the fact that `ghcide` is in `build-tool-depends` should make sure that it appears in PATH and that matches the description in the docs https://cabal.readthedocs.io/en/latest/developing-packages.html?highlight=build-tool-depends#pkg-field-build-tool-depends. Does it not work as expected?

**Comment by jacg** [comment]
### Simple demonstration

If I have no `ghcide` on my `$PATH` before running the tests, then the tests fail with a 

    Exception: ghcide: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

for every test.

### More intricate example

You'll need [this branch](/jacg/ghcide/tree/typed-hole-actions). If I run the following 4 commands:

1. `cabal v2-install exe:ghcide --overwrite-policy=always -w ghc-8.6.4`
2. `cabal v2-run test:ghcide-tests -w ghc-8.6.4 -- -p hole`
3. `cabal v2-install exe:ghcide --overwrite-policy=always -w ghc-8.4.4`
4. `cabal v2-run test:ghcide-tests -w ghc-8.6.4 -- -p hole`

(Note: 1 & 3 install ghcide compiled with GHC 8.6 / 8.4; 2 & 4 run tests for GHC 8.6 on **BOTH** occasions)

then the first test run succeeds, but the second test run fails: specifically it fails on the two tests that are not expected to work and are disabled on 8.4. So it looks like there's a 8.6 client (you can tell it's 8.6 because it runs two tests wich don't run on 8.4) talking to an 8.4 server (you can't tell it's 8.4, because it fails the tests).



Am I doing something wrong in my use of cabal?

**Comment by cocreature** [comment]
Can you try `v2-test` instead of `v2-run`? There are some annoying differences between the two. Note that we also don’t have `ghcide` installed separately on CI so it looks like stack adds it to PATH.

**Comment by ndmitchell** [comment]
I tried this with Stack and it worked fine. Stack does an executable build first and then adjusts the PATH accordingly.

**Comment by jacg** [comment]
`v2-test` seems to be picking up the correct executable.

> There are some annoying differences between the two.

Yes, like

+ inability to pass arguments to test runner in `v2-test`, meaning that I have to run
  - the **whole** test suite
  - in series
  each and every time I want to test anything
+ no output colouring in `v2-test`
+ no progress reporting in `v2-test`: all results dumped to screen only after whole suite finished.

... all of which makes `v2-test` unusable for practical purposes. Or am I simply being incompetent in my use of `v2-test`?

**Comment by cocreature** [comment]
If you use `cabal-install >= 3.0` (which imho you should if you want to use `v2-*` stuff) there is 

* `--test-option` which solves the first issue (although arguably slightly less convenient)
* `--test-option="--color=always"` which solves the second issue (again, slightly less convenient)
* `--test-show-details=streaming` which solves the last issue.

I’ll close this since I think if anything this is a `cabal-install` issue (or not depending on what guarantees they want to provide for `v2-run`).
