### ISSUE TITLE
Code action: Add missing signatures

### ISSUE THREAD

**Issue by maralorn** [digital-asset/ghcide#77]
With #69 merged it should now be possible to offer a code action to deal with the missing signatures warning.

The most simple approach would be to just generate a signature with a typed hole and then let the user use the code action on that one.

A more sophisticated approach would be to fake the typed hole to ghc and then supply the response directly in the code action.

The longer I think about it the better I like the first option, since it gives the user the ability to write an own signature if wished, the other solution actually sounds a bit complex to implement.

**Comment by ndmitchell** [comment]
When I add ` -Wmissing-signatures` I get:

```
C:\Neil\foo.hs:5:1: warning:
    Top-level binding with no type signature:
      foo :: (Eq a, Num a, Num p) => a -> p 
```

Maybe ghcide should always turn on this warning, always suggest it as a code action, but then if the user didn't turn on this warning, suppress the resulting warning notification. I don't think there's any need to play with type holes.

**Comment by hsenag** [comment]
The advantage of doing it directly is you won't end up with the redundant ()s you get from using type wildcards. (See #27 - typed holes is about filling in _s at the expression level.)

**Comment by maralorn** [comment]
Okay, yeah. Perhaps one could reuse code from the typed holes action to get the Code out of the error message.

**Comment by hsenag** [comment]
I think several of the code actions have to do it (mostly with ad-hoc string processing). The error message above looks simpler than most as it starts on a new line.

**Comment by jacg** [comment]
How would you turn `-Wmissing-signatures` on/off programatically in a ghcide test, to verify the behaviour?

**Comment by hsenag** [comment]
> How would you turn `-Wmissing-signatures` on/off programatically in a ghcide test, to verify the behaviour?

Easiest would be to use a pragma in the test code:
```
{-# OPTIONS_GHC -Wmissing-signatures #-}
{-# OPTIONS_GHC -Wno-missing-signatures #-}
```

**Comment by jacg** [comment]
Prototype implementation available in #81.

**Comment by ndmitchell** [comment]
I think this now needs closing, as its available both as a code action and a code lens.

**Comment by cocreature** [comment]
Thanks!
