### ISSUE TITLE
Consider CLA/DCO differences

### ISSUE THREAD

**Issue by ndmitchell** [digital-asset/ghcide#9]
Following MuniHac, a number of people asked questions about the CLA. So the feedback reaches DA, I thought I'd write it here (there may be no actions to take as a result).

* The CLA clause 3 is inelegantly worded. It says:

> You represent that each of Your Contributions is Your original creation. You represent that Your Contribution submissions include complete details of any third-party license or other restriction of which you are personally aware and which are associated with any part of Your Contributions.

But it's quite reasonable to submit third party code to DAML, eg. snippets copied from StackOverflow, provided you represent they are freely licensable as Apache2. If the first full stop is a considered an OR then it's allowed already.

* There was a remark that a CLA typically gives the company copyright allowing them to relicense it. The DA CLA doesn't, so it's really a DCO - a Developer Certificate of Origin. Perhaps making the CLA literally the DCO https://developercertificate.org/ would remove friction? Perhaps just getting more inspiration from it? I had several people say they wouldn't sign a CLA, and then later realise that the DA CLA isn't what they think of as a CLA.

**Comment by ndmitchell** [comment]
Note that I intend to have discussions with other people about this issue in the context of what IDE's should be the default for Haskell. If you have any updates on where you are internally, it would be great to hear them.

**Comment by hurryabit** [comment]
We would prefer to keep a CLA instead of a DCO for the sake of consistency with the `daml` repo, which needs a license agreement. However, we're happy change the third clause to

> You represent that each of Your Contributions is Your original creation. You represent that Your Contribution submissions include complete details of any third-party license or other restriction of which you are personally aware and which are associated with any part of Your Contributions **that would restrict Digital Asset's use of your Contribution**.

if that improves the situation.

**Comment by ndmitchell** [comment]
Saying the words Digital Asset more in the CLA doesn't help the people who don't like companies anyway. It wouldn't then allow submitting third-party code, so it's still the same state as before. Better to leave it as is.

I think it's worth mentioning the CLA in the README so it isn't a nasty surprise halfway through development. I've submitted a patch for that https://github.com/digital-asset/ghcide/pull/128

Thanks for considering it, I'll close this ticket and we now have a firm answer.
