### ISSUE TITLE
hs-boot file support

### ISSUE THREAD

**Issue by mpickering** [digital-asset/ghcide#96]
Are hs-boot files supported yet?

I want to try the project on GHC but there are many hs-boot files.

**Comment by ndmitchell** [comment]
Yep, @hsenag did the work in https://github.com/digital-asset/ghcide/commit/87c68e102987fe86cf18455576b2fa918450ab77

**Comment by mpickering** [comment]
Great, I'll try it tomorrow then and report back if there are any issues. Thanks Ganesh!
