### ISSUE TITLE
Is initializeFlagsWithCradle the right function?

### ISSUE THREAD

**Issue by mpickering** [digital-asset/ghcide#99]
`initializeFlagsWithCradle` currently loads the entire project using GHC's existing downsweep mechanism. Is this necessary for `ghcide`? 

Should I refactor the API to provide a separate way to start the session without calling `depanal` and `load'`?

**Comment by ndmitchell** [comment]
I think `initSession` does exactly that, and has exactly the right API we're after, and moreover returns additional information about the targets. So I think on the `hie-bios` side we're done, it's just the `ghcide` side.

**Comment by ndmitchell** [comment]
See #102 - we can be twice as fast without it.
